//
// Generated for Cardess.SELL
// https://github.com/yonaskolb/SwagGen
//  
//  Generated by Ilya Mikhailov
//  Copyright © 2022 MCon Germany GmbH. All rights reserved.

import Foundation



public class AccessoryInfo: Codable, Equatable {
  public var carlines: [String]?
  public var description: String?
  public var externalId: String?
  public var fitments: [String]?
  public var id: String?
  public var imageUrl: String?
  public var itemPrice: Double?
  public var name: String?
  public var priceBrutto: Double?

  public init(carlines: [String]?  = nil, description: String?  = nil, externalId: String?  = nil, fitments: [String]?  = nil, id: String? = nil, imageUrl: String?  = nil, itemPrice: Double?  = nil, name: String?  = nil, priceBrutto: Double?  = nil) {
    self.carlines = carlines
    self.description = description
    self.externalId = externalId
    self.fitments = fitments
    self.id = id
    self.imageUrl = imageUrl
    self.itemPrice = itemPrice
    self.name = name
    self.priceBrutto = priceBrutto
  }


  public func isEqual(to object: Any?) -> Bool {
    guard let object = object as? AccessoryInfo else { return false }
    guard self.carlines == object.carlines else { return false }
    guard self.description == object.description else { return false }
    guard self.externalId == object.externalId else { return false }
    guard self.fitments == object.fitments else { return false }
    guard self.id == object.id else { return false }
    guard self.imageUrl == object.imageUrl else { return false }
    guard self.itemPrice == object.itemPrice else { return false }
    guard self.name == object.name else { return false }
    guard self.priceBrutto == object.priceBrutto else { return false }
    return true
  }

  public static func == (lhs: AccessoryInfo, rhs: AccessoryInfo) -> Bool {
    return lhs.isEqual(to: rhs)
  }
}
