//
// Generated for Cardess.SELL
// https://github.com/yonaskolb/SwagGen
//  
//  Generated by Ilya Mikhailov
//  Copyright © 2022 MCon Germany GmbH. All rights reserved.

import Foundation



public class AnalyticsServiceCapacityData: Codable, Equatable {
  public var noFollowUpPlannedDuration: Double?
  public var noFollowUpPlannedIds: [String]?
  public var noFollowUpPlannedQuantity: Int?
  public var overduedDuration: Double?
  public var overduedIds: [String]?
  public var overduedQuantity: Int?
  public var plannedForTodayDuration: Double?
  public var plannedForTodayIds: [String]?
  public var plannedForTodayQuantity: Int?
  public var rowId: String?
  public var rowName: String?

  public init(noFollowUpPlannedDuration: Double?  = nil, noFollowUpPlannedIds: [String]?  = nil, noFollowUpPlannedQuantity: Int?  = nil, overduedDuration: Double?  = nil, overduedIds: [String]?  = nil, overduedQuantity: Int?  = nil, plannedForTodayDuration: Double?  = nil, plannedForTodayIds: [String]?  = nil, plannedForTodayQuantity: Int?  = nil, rowId: String?  = nil, rowName: String?  = nil) {
    self.noFollowUpPlannedDuration = noFollowUpPlannedDuration
    self.noFollowUpPlannedIds = noFollowUpPlannedIds
    self.noFollowUpPlannedQuantity = noFollowUpPlannedQuantity
    self.overduedDuration = overduedDuration
    self.overduedIds = overduedIds
    self.overduedQuantity = overduedQuantity
    self.plannedForTodayDuration = plannedForTodayDuration
    self.plannedForTodayIds = plannedForTodayIds
    self.plannedForTodayQuantity = plannedForTodayQuantity
    self.rowId = rowId
    self.rowName = rowName
  }


  public func isEqual(to object: Any?) -> Bool {
    guard let object = object as? AnalyticsServiceCapacityData else { return false }
    guard self.noFollowUpPlannedDuration == object.noFollowUpPlannedDuration else { return false }
    guard self.noFollowUpPlannedIds == object.noFollowUpPlannedIds else { return false }
    guard self.noFollowUpPlannedQuantity == object.noFollowUpPlannedQuantity else { return false }
    guard self.overduedDuration == object.overduedDuration else { return false }
    guard self.overduedIds == object.overduedIds else { return false }
    guard self.overduedQuantity == object.overduedQuantity else { return false }
    guard self.plannedForTodayDuration == object.plannedForTodayDuration else { return false }
    guard self.plannedForTodayIds == object.plannedForTodayIds else { return false }
    guard self.plannedForTodayQuantity == object.plannedForTodayQuantity else { return false }
    guard self.rowId == object.rowId else { return false }
    guard self.rowName == object.rowName else { return false }
    return true
  }

  public static func == (lhs: AnalyticsServiceCapacityData, rhs: AnalyticsServiceCapacityData) -> Bool {
    return lhs.isEqual(to: rhs)
  }
}
