//
// Generated for Cardess.SELL
// https://github.com/yonaskolb/SwagGen
//  
//  Generated by Ilya Mikhailov
//  Copyright © 2022 MCon Germany GmbH. All rights reserved.

import Foundation



public class AnalyticsServiceLeadStatisticsData: Codable, Equatable {
  public var appointmentConfirmed: Bool?
  public var appointmentNotConfirmed: Bool?
  public var channel: AnalyticsServiceEnumsLeadChannel?
  public var contacted: Bool?
  public var contractCreated: Bool?
  public var deliveryPlanned: Bool?
  public var leadId: String?
  public var notContacted: Bool?
  public var offerMade: Bool?
  public var rowId: String?
  public var rowName: String?
  public var source: CustomerDataEnumsLeadSource?
  public var testDrivesPerformed: Bool?
  public var won: Bool?

  public init(appointmentConfirmed: Bool?  = nil, appointmentNotConfirmed: Bool?  = nil, channel: AnalyticsServiceEnumsLeadChannel?  = nil, contacted: Bool?  = nil, contractCreated: Bool?  = nil, deliveryPlanned: Bool?  = nil, leadId: String? = nil, notContacted: Bool?  = nil, offerMade: Bool?  = nil, rowId: String?  = nil, rowName: String?  = nil, source: CustomerDataEnumsLeadSource?  = nil, testDrivesPerformed: Bool?  = nil, won: Bool?  = nil) {
    self.appointmentConfirmed = appointmentConfirmed
    self.appointmentNotConfirmed = appointmentNotConfirmed
    self.channel = channel
    self.contacted = contacted
    self.contractCreated = contractCreated
    self.deliveryPlanned = deliveryPlanned
    self.leadId = leadId
    self.notContacted = notContacted
    self.offerMade = offerMade
    self.rowId = rowId
    self.rowName = rowName
    self.source = source
    self.testDrivesPerformed = testDrivesPerformed
    self.won = won
  }


  public func isEqual(to object: Any?) -> Bool {
    guard let object = object as? AnalyticsServiceLeadStatisticsData else { return false }
    guard self.appointmentConfirmed == object.appointmentConfirmed else { return false }
    guard self.appointmentNotConfirmed == object.appointmentNotConfirmed else { return false }
    guard self.channel == object.channel else { return false }
    guard self.contacted == object.contacted else { return false }
    guard self.contractCreated == object.contractCreated else { return false }
    guard self.deliveryPlanned == object.deliveryPlanned else { return false }
    guard self.leadId == object.leadId else { return false }
    guard self.notContacted == object.notContacted else { return false }
    guard self.offerMade == object.offerMade else { return false }
    guard self.rowId == object.rowId else { return false }
    guard self.rowName == object.rowName else { return false }
    guard self.source == object.source else { return false }
    guard self.testDrivesPerformed == object.testDrivesPerformed else { return false }
    guard self.won == object.won else { return false }
    return true
  }

  public static func == (lhs: AnalyticsServiceLeadStatisticsData, rhs: AnalyticsServiceLeadStatisticsData) -> Bool {
    return lhs.isEqual(to: rhs)
  }
}
