//
// Generated for Cardess.SELL
// https://github.com/yonaskolb/SwagGen
//  
//  Generated by Ilya Mikhailov
//  Copyright © 2022 MCon Germany GmbH. All rights reserved.

import Foundation



public class ApplicationClientInfo: Codable, Equatable {
  public var id: String?
  public var name: String?
  public var secrets: [ApplicationClientSecretInfo]?

  public init(id: String? = nil, name: String?  = nil, secrets: [ApplicationClientSecretInfo]?  = nil) {
    self.id = id
    self.name = name
    self.secrets = secrets
  }


  public func isEqual(to object: Any?) -> Bool {
    guard let object = object as? ApplicationClientInfo else { return false }
    guard self.id == object.id else { return false }
    guard self.name == object.name else { return false }
    guard self.secrets == object.secrets else { return false }
    return true
  }

  public static func == (lhs: ApplicationClientInfo, rhs: ApplicationClientInfo) -> Bool {
    return lhs.isEqual(to: rhs)
  }
}
