//
// Generated for Cardess.SELL
// https://github.com/yonaskolb/SwagGen
//  
//  Generated by Ilya Mikhailov
//  Copyright © 2022 MCon Germany GmbH. All rights reserved.

import Foundation



public class BaseDocmosisRenderRequest: Codable, Equatable {
  public var outputFormat: String?
  public var outputName: String?
  public var templateName: String?

  public init(outputFormat: String?  = nil, outputName: String?  = nil, templateName: String?  = nil) {
    self.outputFormat = outputFormat
    self.outputName = outputName
    self.templateName = templateName
  }


  public func isEqual(to object: Any?) -> Bool {
    guard let object = object as? BaseDocmosisRenderRequest else { return false }
    guard self.outputFormat == object.outputFormat else { return false }
    guard self.outputName == object.outputName else { return false }
    guard self.templateName == object.templateName else { return false }
    return true
  }

  public static func == (lhs: BaseDocmosisRenderRequest, rhs: BaseDocmosisRenderRequest) -> Bool {
    return lhs.isEqual(to: rhs)
  }
}
