//
// Generated for Cardess.SELL
// https://github.com/yonaskolb/SwagGen
//  
//  Generated by Ilya Mikhailov
//  Copyright © 2022 MCon Germany GmbH. All rights reserved.

import Foundation



public class BDCLocationActivities: Codable, Equatable {
  public var activities: [ActivityInfo]?
  public var location: CommunicationLocationInfo?
  public var users: [UserInfo]?

  public init(activities: [ActivityInfo]?  = nil, location: CommunicationLocationInfo?  = nil, users: [UserInfo]?  = nil) {
    self.activities = activities
    self.location = location
    self.users = users
  }


  public func isEqual(to object: Any?) -> Bool {
    guard let object = object as? BDCLocationActivities else { return false }
    guard self.activities == object.activities else { return false }
    guard self.location == object.location else { return false }
    guard self.users == object.users else { return false }
    return true
  }

  public static func == (lhs: BDCLocationActivities, rhs: BDCLocationActivities) -> Bool {
    return lhs.isEqual(to: rhs)
  }
}
