//
// Generated for Cardess.SELL
// https://github.com/yonaskolb/SwagGen
//  
//  Generated by Ilya Mikhailov
//  Copyright © 2022 MCon Germany GmbH. All rights reserved.

import Foundation

public enum CommunicationRemoteConsultingRemoteServiceCaseState: Int, Codable, Equatable, CaseIterable {
    case notAuthored = 0
    case new = 1
    case inProgress = 2
    case done = 3
    case rejected = 4
    case canceled = 5
}
