//
// Generated for Cardess.SELL
// https://github.com/yonaskolb/SwagGen
//  
//  Generated by Ilya Mikhailov
//  Copyright © 2022 MCon Germany GmbH. All rights reserved.

import Foundation



public class CommunicationServiceEntity: Codable, Equatable {
  public var id: String?
  public var name: String?
  public var sample: String?

  public init(id: String? = nil, name: String?  = nil, sample: String?  = nil) {
    self.id = id
    self.name = name
    self.sample = sample
  }


  public func isEqual(to object: Any?) -> Bool {
    guard let object = object as? CommunicationServiceEntity else { return false }
    guard self.id == object.id else { return false }
    guard self.name == object.name else { return false }
    guard self.sample == object.sample else { return false }
    return true
  }

  public static func == (lhs: CommunicationServiceEntity, rhs: CommunicationServiceEntity) -> Bool {
    return lhs.isEqual(to: rhs)
  }
}
