//
// Generated for Cardess.SELL
// https://github.com/yonaskolb/SwagGen
//  
//  Generated by Ilya Mikhailov
//  Copyright © 2022 MCon Germany GmbH. All rights reserved.

import Foundation

public enum CommunicationServiceEnumsEventSenderType: Int, Codable, Equatable, CaseIterable {
    case location = 0
    case salesPerson = 1
    case staticEmail = 2
}
