//
// Generated for Cardess.SELL
// https://github.com/yonaskolb/SwagGen
//  
//  Generated by Ilya Mikhailov
//  Copyright © 2022 MCon Germany GmbH. All rights reserved.

import Foundation

public enum CommunicationModelsEnumsLeadVehicleType: Int, Codable, Equatable, CaseIterable {
    case interest = 0
    case notInteresting = 1
    case quoteRequested = 2
    case quoteProvided = 3
    case orderRequested = 4
    case orderProvided = 5
    case orderAccepted = 6
    case deliveryPlanned = 7
    case delivered = 8
}
