//
// Generated for Cardess.SELL
// https://github.com/yonaskolb/SwagGen
//  
//  Generated by Ilya Mikhailov
//  Copyright © 2022 MCon Germany GmbH. All rights reserved.

import Foundation



public class CommunicationTradeInEvaluationWeight: Codable, Equatable {
  public var autofokus24Weight: Int?
  public var datWeight: Int?
  public var schwackeWeight: Int?

  public init(autofokus24Weight: Int?  = nil, datWeight: Int?  = nil, schwackeWeight: Int?  = nil) {
    self.autofokus24Weight = autofokus24Weight
    self.datWeight = datWeight
    self.schwackeWeight = schwackeWeight
  }


  public func isEqual(to object: Any?) -> Bool {
    guard let object = object as? CommunicationTradeInEvaluationWeight else { return false }
    guard self.autofokus24Weight == object.autofokus24Weight else { return false }
    guard self.datWeight == object.datWeight else { return false }
    guard self.schwackeWeight == object.schwackeWeight else { return false }
    return true
  }

  public static func == (lhs: CommunicationTradeInEvaluationWeight, rhs: CommunicationTradeInEvaluationWeight) -> Bool {
    return lhs.isEqual(to: rhs)
  }
}
