//
// Generated for Cardess.SELL
// https://github.com/yonaskolb/SwagGen
//  
//  Generated by Ilya Mikhailov
//  Copyright © 2022 MCon Germany GmbH. All rights reserved.

import Foundation



public class CommunicationTradeInModifiedValuation: Codable, Equatable {
  public var fiCodeMatchLevel: Int?
  public var modifiedPriceFrom: CommunicationTradeInMonetaryValue?
  public var modifiedPriceTo: CommunicationTradeInMonetaryValue?

  public init(fiCodeMatchLevel: Int?  = nil, modifiedPriceFrom: CommunicationTradeInMonetaryValue?  = nil, modifiedPriceTo: CommunicationTradeInMonetaryValue?  = nil) {
    self.fiCodeMatchLevel = fiCodeMatchLevel
    self.modifiedPriceFrom = modifiedPriceFrom
    self.modifiedPriceTo = modifiedPriceTo
  }


  public func isEqual(to object: Any?) -> Bool {
    guard let object = object as? CommunicationTradeInModifiedValuation else { return false }
    guard self.fiCodeMatchLevel == object.fiCodeMatchLevel else { return false }
    guard self.modifiedPriceFrom == object.modifiedPriceFrom else { return false }
    guard self.modifiedPriceTo == object.modifiedPriceTo else { return false }
    return true
  }

  public static func == (lhs: CommunicationTradeInModifiedValuation, rhs: CommunicationTradeInModifiedValuation) -> Bool {
    return lhs.isEqual(to: rhs)
  }
}
