//
// Generated for Cardess.SELL
// https://github.com/yonaskolb/SwagGen
//  
//  Generated by Ilya Mikhailov
//  Copyright © 2022 MCon Germany GmbH. All rights reserved.

import Foundation



public class CommunicationTradeInRentalContract: Codable, Equatable {
  public var endContractValuationId: String?
  public var endDate: Date?
  public var expectedMileage: Int?
  public var startDate: Date?
  public var startMileage: Int?

  public init(endContractValuationId: String?  = nil, endDate: Date? = nil, expectedMileage: Int?  = nil, startDate: Date? = nil, startMileage: Int?  = nil) {
    self.endContractValuationId = endContractValuationId
    self.endDate = endDate
    self.expectedMileage = expectedMileage
    self.startDate = startDate
    self.startMileage = startMileage
  }


  public func isEqual(to object: Any?) -> Bool {
    guard let object = object as? CommunicationTradeInRentalContract else { return false }
    guard self.endContractValuationId == object.endContractValuationId else { return false }
    guard self.endDate == object.endDate else { return false }
    guard self.expectedMileage == object.expectedMileage else { return false }
    guard self.startDate == object.startDate else { return false }
    guard self.startMileage == object.startMileage else { return false }
    return true
  }

  public static func == (lhs: CommunicationTradeInRentalContract, rhs: CommunicationTradeInRentalContract) -> Bool {
    return lhs.isEqual(to: rhs)
  }
}
