//
// Generated for Cardess.SELL
// https://github.com/yonaskolb/SwagGen
//  
//  Generated by Ilya Mikhailov
//  Copyright © 2022 MCon Germany GmbH. All rights reserved.

import Foundation

public enum CommunicationRemoteConsultingProcessType: Int, Codable, Equatable, CaseIterable {
    case rsc = 0
    case carcheck = 1
    case imageCollector = 2
}
