//
// Generated for Cardess.SELL
// https://github.com/yonaskolb/SwagGen
//  
//  Generated by Ilya Mikhailov
//  Copyright © 2022 MCon Germany GmbH. All rights reserved.

import Foundation



public class CommunicationTaxonomyTranslation: Codable, Equatable {
  public var countryCode: String?
  public var languageCode: String?
  public var translation: String?
  public var translationLong: String?

  public init(countryCode: String?  = nil, languageCode: String?  = nil, translation: String?  = nil, translationLong: String?  = nil) {
    self.countryCode = countryCode
    self.languageCode = languageCode
    self.translation = translation
    self.translationLong = translationLong
  }


  public func isEqual(to object: Any?) -> Bool {
    guard let object = object as? CommunicationTaxonomyTranslation else { return false }
    guard self.countryCode == object.countryCode else { return false }
    guard self.languageCode == object.languageCode else { return false }
    guard self.translation == object.translation else { return false }
    guard self.translationLong == object.translationLong else { return false }
    return true
  }

  public static func == (lhs: CommunicationTaxonomyTranslation, rhs: CommunicationTaxonomyTranslation) -> Bool {
    return lhs.isEqual(to: rhs)
  }
}
