//
// Generated for Cardess.SELL
// https://github.com/yonaskolb/SwagGen
//  
//  Generated by Ilya Mikhailov
//  Copyright © 2022 MCon Germany GmbH. All rights reserved.

import Foundation



public class CommunicationServiceRenderedMessage: Codable, Equatable {
  public var htmlContent: String?
  public var plainContent: String?
  public var subject: String?

  public init(htmlContent: String?  = nil, plainContent: String?  = nil, subject: String?  = nil) {
    self.htmlContent = htmlContent
    self.plainContent = plainContent
    self.subject = subject
  }


  public func isEqual(to object: Any?) -> Bool {
    guard let object = object as? CommunicationServiceRenderedMessage else { return false }
    guard self.htmlContent == object.htmlContent else { return false }
    guard self.plainContent == object.plainContent else { return false }
    guard self.subject == object.subject else { return false }
    return true
  }

  public static func == (lhs: CommunicationServiceRenderedMessage, rhs: CommunicationServiceRenderedMessage) -> Bool {
    return lhs.isEqual(to: rhs)
  }
}
