//
// Generated for Cardess.SELL
// https://github.com/yonaskolb/SwagGen
//  
//  Generated by Ilya Mikhailov
//  Copyright © 2022 MCon Germany GmbH. All rights reserved.

import Foundation



public class CommunicationTradeInCaseVehicleSimple: Codable, Equatable {
  public var baseModelName: String?
  public var licensePlate: String?
  public var manufactureName: String?
  public var registrationDate: Date?
  public var vehicleId: String?
  public var vin: String?

  public init(baseModelName: String?  = nil, licensePlate: String?  = nil, manufactureName: String?  = nil, registrationDate: Date? = nil, vehicleId: String?  = nil, vin: String?  = nil) {
    self.baseModelName = baseModelName
    self.licensePlate = licensePlate
    self.manufactureName = manufactureName
    self.registrationDate = registrationDate
    self.vehicleId = vehicleId
    self.vin = vin
  }


  public func isEqual(to object: Any?) -> Bool {
    guard let object = object as? CommunicationTradeInCaseVehicleSimple else { return false }
    guard self.baseModelName == object.baseModelName else { return false }
    guard self.licensePlate == object.licensePlate else { return false }
    guard self.manufactureName == object.manufactureName else { return false }
    guard self.registrationDate == object.registrationDate else { return false }
    guard self.vehicleId == object.vehicleId else { return false }
    guard self.vin == object.vin else { return false }
    return true
  }

  public static func == (lhs: CommunicationTradeInCaseVehicleSimple, rhs: CommunicationTradeInCaseVehicleSimple) -> Bool {
    return lhs.isEqual(to: rhs)
  }
}
