//
// Generated for Cardess.SELL
// https://github.com/yonaskolb/SwagGen
//  
//  Generated by Ilya Mikhailov
//  Copyright © 2022 MCon Germany GmbH. All rights reserved.

import Foundation



public class CommunicationImportImportBulkResponse: Codable, Equatable {
  public var response: [CommunicationImportImportResponse]?

  public init(response: [CommunicationImportImportResponse]?  = nil) {
    self.response = response
  }


  public func isEqual(to object: Any?) -> Bool {
    guard let object = object as? CommunicationImportImportBulkResponse else { return false }
    guard self.response == object.response else { return false }
    return true
  }

  public static func == (lhs: CommunicationImportImportBulkResponse, rhs: CommunicationImportImportBulkResponse) -> Bool {
    return lhs.isEqual(to: rhs)
  }
}
