//
// Generated for Cardess.SELL
// https://github.com/yonaskolb/SwagGen
//  
//  Generated by Ilya Mikhailov
//  Copyright © 2022 MCon Germany GmbH. All rights reserved.

import Foundation



public class CommunicationPagingQueryParameters: Codable, Equatable {
  public var filter: String?
  public var page: Int?
  public var pageSize: Int?
  public var skipSort: Bool?
  public var sortAscending: Bool?
  public var sortField: String?

  public init(filter: String?  = nil, page: Int?  = nil, pageSize: Int?  = nil, skipSort: Bool?  = nil, sortAscending: Bool?  = nil, sortField: String?  = nil) {
    self.filter = filter
    self.page = page
    self.pageSize = pageSize
    self.skipSort = skipSort
    self.sortAscending = sortAscending
    self.sortField = sortField
  }


  public func isEqual(to object: Any?) -> Bool {
    guard let object = object as? CommunicationPagingQueryParameters else { return false }
    guard self.filter == object.filter else { return false }
    guard self.page == object.page else { return false }
    guard self.pageSize == object.pageSize else { return false }
    guard self.skipSort == object.skipSort else { return false }
    guard self.sortAscending == object.sortAscending else { return false }
    guard self.sortField == object.sortField else { return false }
    return true
  }

  public static func == (lhs: CommunicationPagingQueryParameters, rhs: CommunicationPagingQueryParameters) -> Bool {
    return lhs.isEqual(to: rhs)
  }
}
