//
// Generated for Cardess.SELL
// https://github.com/yonaskolb/SwagGen
//  
//  Generated by Ilya Mikhailov
//  Copyright © 2022 MCon Germany GmbH. All rights reserved.

import Foundation



public class CommunicationRemoteConsultingCustomer: Codable, Equatable {
  public var email: String?
  public var firstName: String?
  public var lastName: String?
  public var latitude: Double?
  public var longitude: Double?
  public var phone: String?

  public init(email: String?  = nil, firstName: String?  = nil, lastName: String?  = nil, latitude: Double?  = nil, longitude: Double?  = nil, phone: String?  = nil) {
    self.email = email
    self.firstName = firstName
    self.lastName = lastName
    self.latitude = latitude
    self.longitude = longitude
    self.phone = phone
  }


  public func isEqual(to object: Any?) -> Bool {
    guard let object = object as? CommunicationRemoteConsultingCustomer else { return false }
    guard self.email == object.email else { return false }
    guard self.firstName == object.firstName else { return false }
    guard self.lastName == object.lastName else { return false }
    guard self.latitude == object.latitude else { return false }
    guard self.longitude == object.longitude else { return false }
    guard self.phone == object.phone else { return false }
    return true
  }

  public static func == (lhs: CommunicationRemoteConsultingCustomer, rhs: CommunicationRemoteConsultingCustomer) -> Bool {
    return lhs.isEqual(to: rhs)
  }
}
