//
// Generated for Cardess.SELL
// https://github.com/yonaskolb/SwagGen
//  
//  Generated by Ilya Mikhailov
//  Copyright © 2022 MCon Germany GmbH. All rights reserved.

import Foundation



public class CommunicationTradeInCaseVehicleRemarks: Codable, Equatable {
  public var lossPercentage: Int?
  public var remark: String?

  public init(lossPercentage: Int?  = nil, remark: String?  = nil) {
    self.lossPercentage = lossPercentage
    self.remark = remark
  }


  public func isEqual(to object: Any?) -> Bool {
    guard let object = object as? CommunicationTradeInCaseVehicleRemarks else { return false }
    guard self.lossPercentage == object.lossPercentage else { return false }
    guard self.remark == object.remark else { return false }
    return true
  }

  public static func == (lhs: CommunicationTradeInCaseVehicleRemarks, rhs: CommunicationTradeInCaseVehicleRemarks) -> Bool {
    return lhs.isEqual(to: rhs)
  }
}
