//
// Generated for Cardess.SELL
// https://github.com/yonaskolb/SwagGen
//  
//  Generated by Ilya Mikhailov
//  Copyright © 2022 MCon Germany GmbH. All rights reserved.

import Foundation



public class CommunicationServiceTemplateLink: Codable, Equatable {
  public var editUrl: String?
  public var id: String?
  public var name: String?

  public init(editUrl: String?  = nil, id: String?  = nil, name: String?  = nil) {
    self.editUrl = editUrl
    self.id = id
    self.name = name
  }


  public func isEqual(to object: Any?) -> Bool {
    guard let object = object as? CommunicationServiceTemplateLink else { return false }
    guard self.editUrl == object.editUrl else { return false }
    guard self.id == object.id else { return false }
    guard self.name == object.name else { return false }
    return true
  }

  public static func == (lhs: CommunicationServiceTemplateLink, rhs: CommunicationServiceTemplateLink) -> Bool {
    return lhs.isEqual(to: rhs)
  }
}
