//
// Generated for Cardess.SELL
// https://github.com/yonaskolb/SwagGen
//  
//  Generated by Ilya Mikhailov
//  Copyright © 2022 MCon Germany GmbH. All rights reserved.

import Foundation

public enum CommunicationTradeInValuationSource: Int, Codable, Equatable, CaseIterable {
    case dat = 0
    case fairgarage = 1
}
