//
// Generated for Cardess.SELL
// https://github.com/yonaskolb/SwagGen
//  
//  Generated by Ilya Mikhailov
//  Copyright © 2022 MCon Germany GmbH. All rights reserved.

import Foundation



public class CommunicationTaxonomyValue<T:Codable>: Codable, Equatable {
  public var dimensionTypeId: String?
  public var externalId: String?
  public var id: String?
  public var name: String?
  public var translations: [CommunicationTaxonomyTranslation]?
  public var value: T?

  public init(dimensionTypeId: String?  = nil, externalId: String?  = nil, id: String?  = nil, name: String?  = nil, translations: [CommunicationTaxonomyTranslation]?  = nil, value: T? = nil) {
    self.dimensionTypeId = dimensionTypeId
    self.externalId = externalId
    self.id = id
    self.name = name
    self.translations = translations
    self.value = value
  }


  public func isEqual(to object: Any?) -> Bool {
    guard let object = object as? CommunicationTaxonomyValue else { return false }
    guard self.dimensionTypeId == object.dimensionTypeId else { return false }
    guard self.externalId == object.externalId else { return false }
    guard self.id == object.id else { return false }
    guard self.name == object.name else { return false }
    guard self.translations == object.translations else { return false }
    // guard self.value == object.value else { return false }
    return true
  }

  public static func == (lhs: CommunicationTaxonomyValue, rhs: CommunicationTaxonomyValue) -> Bool {
    return lhs.isEqual(to: rhs)
  }
}
