//
// Generated for Cardess.SELL
// https://github.com/yonaskolb/SwagGen
//  
//  Generated by Ilya Mikhailov
//  Copyright © 2022 MCon Germany GmbH. All rights reserved.

import Foundation



public class CommunicationEventMapping: Codable, Equatable {
  public var eventCode: EnumsEventType?
  public var types: [CommunicationEventMappingType]?

  public init(eventCode: EnumsEventType?  = nil, types: [CommunicationEventMappingType]?  = nil) {
    self.eventCode = eventCode
    self.types = types
  }


  public func isEqual(to object: Any?) -> Bool {
    guard let object = object as? CommunicationEventMapping else { return false }
    guard self.eventCode == object.eventCode else { return false }
    guard self.types == object.types else { return false }
    return true
  }

  public static func == (lhs: CommunicationEventMapping, rhs: CommunicationEventMapping) -> Bool {
    return lhs.isEqual(to: rhs)
  }
}
