//
// Generated for Cardess.SELL
// https://github.com/yonaskolb/SwagGen
//  
//  Generated by Ilya Mikhailov
//  Copyright © 2022 MCon Germany GmbH. All rights reserved.

import Foundation



public class CommunicationTradeInCaseStatusHistory: Codable, Equatable {
  public var date: Date?
  public var status: CommunicationTradeInCaseStatus?

  public init(date: Date? = nil, status: CommunicationTradeInCaseStatus?  = nil) {
    self.date = date
    self.status = status
  }


  public func isEqual(to object: Any?) -> Bool {
    guard let object = object as? CommunicationTradeInCaseStatusHistory else { return false }
    guard self.date == object.date else { return false }
    guard self.status == object.status else { return false }
    return true
  }

  public static func == (lhs: CommunicationTradeInCaseStatusHistory, rhs: CommunicationTradeInCaseStatusHistory) -> Bool {
    return lhs.isEqual(to: rhs)
  }
}
