//
// Generated for Cardess.SELL
// https://github.com/yonaskolb/SwagGen
//  
//  Generated by Ilya Mikhailov
//  Copyright © 2022 MCon Germany GmbH. All rights reserved.

import Foundation

public enum CommunicationTradeInValuationType: Int, Codable, Equatable, CaseIterable {
    case evaluation = 0
    case approximate = 1
    case forecast = 2
}
