//
// Generated for Cardess.SELL
// https://github.com/yonaskolb/SwagGen
//  
//  Generated by Ilya Mikhailov
//  Copyright © 2022 MCon Germany GmbH. All rights reserved.

import Foundation



public class CommunicationRemoteConsultingCallInfo: Codable, Equatable {
  public var callAnsweredAt: Date?
  public var callAnsweredBy: String?

  public init(callAnsweredAt: Date? = nil, callAnsweredBy: String?  = nil) {
    self.callAnsweredAt = callAnsweredAt
    self.callAnsweredBy = callAnsweredBy
  }


  public func isEqual(to object: Any?) -> Bool {
    guard let object = object as? CommunicationRemoteConsultingCallInfo else { return false }
    guard self.callAnsweredAt == object.callAnsweredAt else { return false }
    guard self.callAnsweredBy == object.callAnsweredBy else { return false }
    return true
  }

  public static func == (lhs: CommunicationRemoteConsultingCallInfo, rhs: CommunicationRemoteConsultingCallInfo) -> Bool {
    return lhs.isEqual(to: rhs)
  }
}
