//
// Generated for Cardess.SELL
// https://github.com/yonaskolb/SwagGen
//  
//  Generated by Ilya Mikhailov
//  Copyright © 2022 MCon Germany GmbH. All rights reserved.

import Foundation

public enum CommunicationTradeInResourceFileType: Int, Codable, Equatable, CaseIterable {
    case application = 0
    case archive = 1
    case audio = 2
    case document = 3
    case image = 4
    case pdf = 5
    case presentation = 6
    case spreadsheet = 7
    case text = 8
    case unknown = 9
    case video = 10
    case mail = 11
}
