//
// Generated for Cardess.SELL
// https://github.com/yonaskolb/SwagGen
//  
//  Generated by Ilya Mikhailov
//  Copyright © 2022 MCon Germany GmbH. All rights reserved.

import Foundation



public class CommunicationTradeInMonetaryValue: Codable, Equatable {
  public var currency: String?
  public var value: Double?

  public init(currency: String?  = nil, value: Double?  = nil) {
    self.currency = currency
    self.value = value
  }


  public func isEqual(to object: Any?) -> Bool {
    guard let object = object as? CommunicationTradeInMonetaryValue else { return false }
    guard self.currency == object.currency else { return false }
    guard self.value == object.value else { return false }
    return true
  }

  public static func == (lhs: CommunicationTradeInMonetaryValue, rhs: CommunicationTradeInMonetaryValue) -> Bool {
    return lhs.isEqual(to: rhs)
  }
}
