//
// Generated for Cardess.SELL
// https://github.com/yonaskolb/SwagGen
//  
//  Generated by Ilya Mikhailov
//  Copyright © 2022 MCon Germany GmbH. All rights reserved.

import Foundation

public enum CommunicationModelsEnumsRejectionReason: Int, Codable, Equatable, CaseIterable {
    case other = 0
    case tooExpensive = 1
    case anotherChose = 2
}
