//
// Generated for Cardess.SELL
// https://github.com/yonaskolb/SwagGen
//  
//  Generated by Ilya Mikhailov
//  Copyright © 2022 MCon Germany GmbH. All rights reserved.

import Foundation

public enum CommunicationServiceEnumsExternalDeliveryState: Int, Codable, Equatable, CaseIterable {
    case processed = 0
    case dropped = 1
    case deferred = 2
    case bounce = 3
    case delivered = 4
}
