//
// Generated for Cardess.SELL
// https://github.com/yonaskolb/SwagGen
//  
//  Generated by Ilya Mikhailov
//  Copyright © 2022 MCon Germany GmbH. All rights reserved.

import Foundation



public class CommunicationTradeInCaseLeadSimple: Codable, Equatable {
  public var email: String?
  public var firstName: String?
  public var lastName: String?
  public var phoneNumber: String?
  public var salutation: String?

  public init(email: String?  = nil, firstName: String?  = nil, lastName: String?  = nil, phoneNumber: String?  = nil, salutation: String?  = nil) {
    self.email = email
    self.firstName = firstName
    self.lastName = lastName
    self.phoneNumber = phoneNumber
    self.salutation = salutation
  }


  public func isEqual(to object: Any?) -> Bool {
    guard let object = object as? CommunicationTradeInCaseLeadSimple else { return false }
    guard self.email == object.email else { return false }
    guard self.firstName == object.firstName else { return false }
    guard self.lastName == object.lastName else { return false }
    guard self.phoneNumber == object.phoneNumber else { return false }
    guard self.salutation == object.salutation else { return false }
    return true
  }

  public static func == (lhs: CommunicationTradeInCaseLeadSimple, rhs: CommunicationTradeInCaseLeadSimple) -> Bool {
    return lhs.isEqual(to: rhs)
  }
}
