//
// Generated for Cardess.SELL
// https://github.com/yonaskolb/SwagGen
//  
//  Generated by Ilya Mikhailov
//  Copyright © 2022 MCon Germany GmbH. All rights reserved.

import Foundation



public class ControllersLeadImportControllerFacebookRegisterRequest: Codable, Equatable {
  public var accessToken: String?
  public var waBusinessID: String?
  public var waPhoneNumberID: String?

  public init(accessToken: String?  = nil, waBusinessID: String?  = nil, waPhoneNumberID: String?  = nil) {
    self.accessToken = accessToken
    self.waBusinessID = waBusinessID
    self.waPhoneNumberID = waPhoneNumberID
  }


  public func isEqual(to object: Any?) -> Bool {
    guard let object = object as? ControllersLeadImportControllerFacebookRegisterRequest else { return false }
    guard self.accessToken == object.accessToken else { return false }
    guard self.waBusinessID == object.waBusinessID else { return false }
    guard self.waPhoneNumberID == object.waPhoneNumberID else { return false }
    return true
  }

  public static func == (lhs: ControllersLeadImportControllerFacebookRegisterRequest, rhs: ControllersLeadImportControllerFacebookRegisterRequest) -> Bool {
    return lhs.isEqual(to: rhs)
  }
}
