//
// Generated for Cardess.SELL
// https://github.com/yonaskolb/SwagGen
//  
//  Generated by Ilya Mikhailov
//  Copyright © 2022 MCon Germany GmbH. All rights reserved.

import Foundation



public class CustomerDataAssignationCustomerInfo: Codable, Equatable {
  public var assignedToId: String?
  public var externalCustomerID: String?
  public var firstName: String?
  public var lastName: String?

  public init(assignedToId: String? = nil, externalCustomerID: String?  = nil, firstName: String?  = nil, lastName: String?  = nil) {
    self.assignedToId = assignedToId
    self.externalCustomerID = externalCustomerID
    self.firstName = firstName
    self.lastName = lastName
  }


  public func isEqual(to object: Any?) -> Bool {
    guard let object = object as? CustomerDataAssignationCustomerInfo else { return false }
    guard self.assignedToId == object.assignedToId else { return false }
    guard self.externalCustomerID == object.externalCustomerID else { return false }
    guard self.firstName == object.firstName else { return false }
    guard self.lastName == object.lastName else { return false }
    return true
  }

  public static func == (lhs: CustomerDataAssignationCustomerInfo, rhs: CustomerDataAssignationCustomerInfo) -> Bool {
    return lhs.isEqual(to: rhs)
  }
}
