//
// Generated for Cardess.SELL
// https://github.com/yonaskolb/SwagGen
//  
//  Generated by Ilya Mikhailov
//  Copyright © 2022 MCon Germany GmbH. All rights reserved.

import Foundation

public enum CustomerPortalEnumsPortalTextType: Int, Codable, Equatable, CaseIterable {
    case consentDefault = 0
    case efficiencyClassHint = 1
    case efficiencyClassHintWltp = 2
    case onlineApplicationProcess = 3
    case offlineApplicationProcess = 4
    case aboAllInclusiveItem = 5
    case iAcceptTermsAndConditions = 6
    case expectedDeliveryTimeText = 7
    case plpSalutationText = 8
    case tireEfficiencyText = 9
    case tradeInDescriptionText = 10
    case fuelConsumptionInfo = 11
    case fuelConsumptionFootnote1 = 12
    case fuelConsumptionFootnote2 = 13
}
