//
// Generated for Cardess.SELL
// https://github.com/yonaskolb/SwagGen
//  
//  Generated by Ilya Mikhailov
//  Copyright © 2022 MCon Germany GmbH. All rights reserved.

import Foundation

public enum CustomerDataEnumsImportCustomerSource: Int, Codable, Equatable, CaseIterable {
    case local = 0
    case unknown = 1
    case haystack = 2
}
