//
// Generated for Cardess.SELL
// https://github.com/yonaskolb/SwagGen
//  
//  Generated by Ilya Mikhailov
//  Copyright © 2022 MCon Germany GmbH. All rights reserved.

import Foundation



public class CustomerPortalPortalTextData: Codable, Equatable {
  public var fullText: String?
  public var id: String?
  public var locale: String?
  public var shortText: String?
  public var type: CustomerPortalEnumsPortalTextType?

  public init(fullText: String?  = nil, id: String? = nil, locale: String?  = nil, shortText: String?  = nil, type: CustomerPortalEnumsPortalTextType?  = nil) {
    self.fullText = fullText
    self.id = id
    self.locale = locale
    self.shortText = shortText
    self.type = type
  }


  public func isEqual(to object: Any?) -> Bool {
    guard let object = object as? CustomerPortalPortalTextData else { return false }
    guard self.fullText == object.fullText else { return false }
    guard self.id == object.id else { return false }
    guard self.locale == object.locale else { return false }
    guard self.shortText == object.shortText else { return false }
    guard self.type == object.type else { return false }
    return true
  }

  public static func == (lhs: CustomerPortalPortalTextData, rhs: CustomerPortalPortalTextData) -> Bool {
    return lhs.isEqual(to: rhs)
  }
}
