//
// Generated for Cardess.SELL
// https://github.com/yonaskolb/SwagGen
//  
//  Generated by Ilya Mikhailov
//  Copyright © 2022 MCon Germany GmbH. All rights reserved.

import Foundation



public class CustomerDataCustomerCurrentVehicleInfo: Codable, Equatable {
  public var ccvId: Int?
  public var created: Date?
  public var externalVehicleId: String?
  public var licensePlate: String?
  public var make: String?
  public var mileage: Int?
  public var model: String?
  public var searchWeight: Int?
  public var vin: String?

  public init(ccvId: Int?  = nil, created: Date? = nil, externalVehicleId: String?  = nil, licensePlate: String?  = nil, make: String?  = nil, mileage: Int?  = nil, model: String?  = nil, searchWeight: Int?  = nil, vin: String?  = nil) {
    self.ccvId = ccvId
    self.created = created
    self.externalVehicleId = externalVehicleId
    self.licensePlate = licensePlate
    self.make = make
    self.mileage = mileage
    self.model = model
    self.searchWeight = searchWeight
    self.vin = vin
  }


  public func isEqual(to object: Any?) -> Bool {
    guard let object = object as? CustomerDataCustomerCurrentVehicleInfo else { return false }
    guard self.ccvId == object.ccvId else { return false }
    guard self.created == object.created else { return false }
    guard self.externalVehicleId == object.externalVehicleId else { return false }
    guard self.licensePlate == object.licensePlate else { return false }
    guard self.make == object.make else { return false }
    guard self.mileage == object.mileage else { return false }
    guard self.model == object.model else { return false }
    guard self.searchWeight == object.searchWeight else { return false }
    guard self.vin == object.vin else { return false }
    return true
  }

  public static func == (lhs: CustomerDataCustomerCurrentVehicleInfo, rhs: CustomerDataCustomerCurrentVehicleInfo) -> Bool {
    return lhs.isEqual(to: rhs)
  }
}
