//
// Generated for Cardess.SELL
// https://github.com/yonaskolb/SwagGen
//  
//  Generated by Ilya Mikhailov
//  Copyright © 2022 MCon Germany GmbH. All rights reserved.

import Foundation



public class DateUsersTimeSlots: Codable, Equatable {
  public var date: Date?
  public var end: Date?
  public var start: Date?
  public var userTimeSlots: [UserTimeSlots]?

  public init(date: Date? = nil, end: Date? = nil, start: Date? = nil, userTimeSlots: [UserTimeSlots]?  = nil) {
    self.date = date
    self.end = end
    self.start = start
    self.userTimeSlots = userTimeSlots
  }


  public func isEqual(to object: Any?) -> Bool {
    guard let object = object as? DateUsersTimeSlots else { return false }
    guard self.date == object.date else { return false }
    guard self.end == object.end else { return false }
    guard self.start == object.start else { return false }
    guard self.userTimeSlots == object.userTimeSlots else { return false }
    return true
  }

  public static func == (lhs: DateUsersTimeSlots, rhs: DateUsersTimeSlots) -> Bool {
    return lhs.isEqual(to: rhs)
  }
}
