//
// Generated for Cardess.SELL
// https://github.com/yonaskolb/SwagGen
//  
//  Generated by Ilya Mikhailov
//  Copyright © 2022 MCon Germany GmbH. All rights reserved.

import Foundation



public class DeliveryBoxBookingInfo: Codable, Equatable {
  public var bookingBy: String?
  public var from: Date?
  public var id: String?
  public var name: String?
  public var to: Date?

  public init(bookingBy: String?  = nil, from: Date? = nil, id: String? = nil, name: String?  = nil, to: Date? = nil) {
    self.bookingBy = bookingBy
    self.from = from
    self.id = id
    self.name = name
    self.to = to
  }


  public func isEqual(to object: Any?) -> Bool {
    guard let object = object as? DeliveryBoxBookingInfo else { return false }
    guard self.bookingBy == object.bookingBy else { return false }
    guard self.from == object.from else { return false }
    guard self.id == object.id else { return false }
    guard self.name == object.name else { return false }
    guard self.to == object.to else { return false }
    return true
  }

  public static func == (lhs: DeliveryBoxBookingInfo, rhs: DeliveryBoxBookingInfo) -> Bool {
    return lhs.isEqual(to: rhs)
  }
}
