//
// Generated for Cardess.SELL
// https://github.com/yonaskolb/SwagGen
//  
//  Generated by Ilya Mikhailov
//  Copyright © 2022 MCon Germany GmbH. All rights reserved.

import Foundation



public class DeliveryBoxInfo: Codable, Equatable {
  public var bookings: [DeliveryBoxBookingInfo]?
  public var id: String?
  public var name: String?
  public var newVehicles: Bool?
  public var slotSizeMinutes: Int?

  public init(bookings: [DeliveryBoxBookingInfo]?  = nil, id: String? = nil, name: String?  = nil, newVehicles: Bool?  = nil, slotSizeMinutes: Int?  = nil) {
    self.bookings = bookings
    self.id = id
    self.name = name
    self.newVehicles = newVehicles
    self.slotSizeMinutes = slotSizeMinutes
  }


  public func isEqual(to object: Any?) -> Bool {
    guard let object = object as? DeliveryBoxInfo else { return false }
    guard self.bookings == object.bookings else { return false }
    guard self.id == object.id else { return false }
    guard self.name == object.name else { return false }
    guard self.newVehicles == object.newVehicles else { return false }
    guard self.slotSizeMinutes == object.slotSizeMinutes else { return false }
    return true
  }

  public static func == (lhs: DeliveryBoxInfo, rhs: DeliveryBoxInfo) -> Bool {
    return lhs.isEqual(to: rhs)
  }
}
