//
// Generated for Cardess.SELL
// https://github.com/yonaskolb/SwagGen
//  
//  Generated by Ilya Mikhailov
//  Copyright © 2022 MCon Germany GmbH. All rights reserved.

import Foundation



public class DynamicEventData: Codable, Equatable {
  public var entityId: String?
  public var entityType: String?
  public var personalMessage: String?
  public var templateId: String?
  public var templateType: CommunicationServiceEnumsTemplateType?

  public init(entityId: String? = nil, entityType: String?  = nil, personalMessage: String?  = nil, templateId: String? = nil, templateType: CommunicationServiceEnumsTemplateType?  = nil) {
    self.entityId = entityId
    self.entityType = entityType
    self.personalMessage = personalMessage
    self.templateId = templateId
    self.templateType = templateType
  }


  public func isEqual(to object: Any?) -> Bool {
    guard let object = object as? DynamicEventData else { return false }
    guard self.entityId == object.entityId else { return false }
    guard self.entityType == object.entityType else { return false }
    guard self.personalMessage == object.personalMessage else { return false }
    guard self.templateId == object.templateId else { return false }
    guard self.templateType == object.templateType else { return false }
    return true
  }

  public static func == (lhs: DynamicEventData, rhs: DynamicEventData) -> Bool {
    return lhs.isEqual(to: rhs)
  }
}
