//
// Generated for Cardess.SELL
// https://github.com/yonaskolb/SwagGen
//  
//  Generated by Ilya Mikhailov
//  Copyright © 2022 MCon Germany GmbH. All rights reserved.

import Foundation

public enum EnumsPersonAvailabilityTime: Int, Codable, Equatable, CaseIterable {
    case everyTime = 0
    case from8to11 = 1
    case from11to14 = 2
    case from14to17 = 3
    case from17to19 = 4
    case from19to20 = 5
}
