//
// Generated for Cardess.SELL
// https://github.com/yonaskolb/SwagGen
//  
//  Generated by Ilya Mikhailov
//  Copyright © 2022 MCon Germany GmbH. All rights reserved.

import Foundation

public enum EnumsLeadType: Int, Codable, Equatable, CaseIterable {
    case sales = 0
    case service = 1
    case generalRequest = 2
}
