//
// Generated for Cardess.SELL
// https://github.com/yonaskolb/SwagGen
//  
//  Generated by Ilya Mikhailov
//  Copyright © 2022 MCon Germany GmbH. All rights reserved.

import Foundation

public enum EnumsDeliveryStatus: Int, Codable, Equatable, CaseIterable {
    case none = 0
    case delivered = 1
    case inProgress = 2
    case failed = 3
    case completed = 4
    case cancelled = 5
}
