//
// Generated for Cardess.SELL
// https://github.com/yonaskolb/SwagGen
//  
//  Generated by Ilya Mikhailov
//  Copyright © 2022 MCon Germany GmbH. All rights reserved.

import Foundation

public enum EnumsLeadVehicleDocumentPurpose: Int, Codable, Equatable, CaseIterable {
    case information = 0
    case toSign = 1
    case signed = 2
    case personalDetails = 3
    case testDrive = 4
    case tradeIn = 5
    case hidden = 6
}
