//
// Generated for Cardess.SELL
// https://github.com/yonaskolb/SwagGen
//  
//  Generated by Ilya Mikhailov
//  Copyright © 2022 MCon Germany GmbH. All rights reserved.

import Foundation

public enum EnumsLeadCloseReason: Int, Codable, Equatable, CaseIterable {
    case none = 0
    case otherCar = 1
    case otherDealer = 2
    case notReachable = 3
    case deferred = 4
    case other = 5
    case incorrectContactInfo = 6
    case refinance = 7
    case keepCurrentCar = 8
    case spam = 9
    case serviceLeadNotReached = 20
    case serviceLeadWrongContactDetails = 25
    case serviceLeadVehicleIsSold = 30
    case serviceLeadNoSlots = 35
    case serviceLeadTooExpensive = 40
    case serviceLeadOtherServicePartner = 41
    case serviceLeadOtherWorkshop = 42
    case serviceLeadCustomerDeceased = 43
    case serviceLeadOther = 45
    case serviceLeadSpam = 50
}
