//
// Generated for Cardess.SELL
// https://github.com/yonaskolb/SwagGen
//  
//  Generated by Ilya Mikhailov
//  Copyright © 2022 MCon Germany GmbH. All rights reserved.

import Foundation

public enum EnumsRequestContactType: Int, Codable, Equatable, CaseIterable {
    case generic = 0
    case appointment = 1
    case testDrive = 2
}
