//
// Generated for Cardess.SELL
// https://github.com/yonaskolb/SwagGen
//  
//  Generated by Ilya Mikhailov
//  Copyright © 2022 MCon Germany GmbH. All rights reserved.

import Foundation

public enum EnumsMessageType: Int, Codable, Equatable, CaseIterable {
    case aiMessage = 0
    case userMessage = 1
    case templateMessage = 2
    case customerMessage = 3
}
