//
// Generated for Cardess.SELL
// https://github.com/yonaskolb/SwagGen
//  
//  Generated by Ilya Mikhailov
//  Copyright © 2022 MCon Germany GmbH. All rights reserved.

import Foundation

public enum EnumsActivityStatus: Int, Codable, Equatable, CaseIterable {
    case `open` = 0
    case completed = 1
    case canceled = 2
    case inProgress = 3
}
