//
// Generated for Cardess.SELL
// https://github.com/yonaskolb/SwagGen
//  
//  Generated by Ilya Mikhailov
//  Copyright © 2022 MCon Germany GmbH. All rights reserved.

import Foundation

public enum EnumsPersonTitle: Int, Codable, Equatable, CaseIterable {
    case mr = 0
    case ms = 1
}
