//
// Generated for Cardess.SELL
// https://github.com/yonaskolb/SwagGen
//  
//  Generated by Ilya Mikhailov
//  Copyright © 2022 MCon Germany GmbH. All rights reserved.

import Foundation

public enum EnumsPersonRelationshipStatus: Int, Codable, Equatable, CaseIterable {
    case inAPartnership = 0
    case single = 1
    case divorced = 2
    case married = 3
    case widowed = 4
    case other = 5
}
