//
// Generated for Cardess.SELL
// https://github.com/yonaskolb/SwagGen
//  
//  Generated by Ilya Mikhailov
//  Copyright © 2022 MCon Germany GmbH. All rights reserved.

import Foundation

public enum EnumsDocumentType: Int, Codable, Equatable, CaseIterable {
    case information = 0
    case insurance = 1
}
