//
// Generated for Cardess.SELL
// https://github.com/yonaskolb/SwagGen
//  
//  Generated by Ilya Mikhailov
//  Copyright © 2022 MCon Germany GmbH. All rights reserved.

import Foundation

public enum EnumsMessageSource: Int, Codable, Equatable, CaseIterable {
    case unknown = 0
    case whatsapp = 1
    case facebook = 2
    case chatplp = 3
}
