//
// Generated for Cardess.SELL
// https://github.com/yonaskolb/SwagGen
//  
//  Generated by Ilya Mikhailov
//  Copyright © 2022 MCon Germany GmbH. All rights reserved.

import Foundation

public enum EnumsCarrierType: Int, Codable, Equatable, CaseIterable {
    case unknown = 0
    case mobile = 1
    case landline = 2
    case voip = 3
}
