//
// Generated for Cardess.SELL
// https://github.com/yonaskolb/SwagGen
//  
//  Generated by Ilya Mikhailov
//  Copyright © 2022 MCon Germany GmbH. All rights reserved.

import Foundation

public enum EnumsLeadVehicleDocumentType: Int, Codable, Equatable, CaseIterable {
    case quote = 0
    case order = 1
    case other = 2
}
