//
// Generated for Cardess.SELL
// https://github.com/yonaskolb/SwagGen
//  
//  Generated by Ilya Mikhailov
//  Copyright © 2022 MCon Germany GmbH. All rights reserved.

import Foundation

public enum EnumsLeadVehicleCalculationType: Int, Codable, Equatable, CaseIterable {
    case calculationRule = 0
    case additionalService = 1
}
