//
// Generated for Cardess.SELL
// https://github.com/yonaskolb/SwagGen
//  
//  Generated by Ilya Mikhailov
//  Copyright © 2022 MCon Germany GmbH. All rights reserved.

import Foundation

public enum EnumsLeadStatus: Int, Codable, Equatable, CaseIterable {
    case `open` = 0
    case win = 1
    case lost = 2
}
