//
// Generated for Cardess.SELL
// https://github.com/yonaskolb/SwagGen
//  
//  Generated by Ilya Mikhailov
//  Copyright © 2022 MCon Germany GmbH. All rights reserved.

import Foundation

public enum EnumsNotificationType: Int, Codable, Equatable, CaseIterable {
    case newLeadCreated = 0
    case leadAssigned = 1
    case offerRequest = 2
    case appointmentRequest = 3
    case firstPlpVisit = 4
}
