//
// Generated for Cardess.SELL
// https://github.com/yonaskolb/SwagGen
//  
//  Generated by Ilya Mikhailov
//  Copyright © 2022 MCon Germany GmbH. All rights reserved.

import Foundation

public enum EnumsLeadExportEvent: Int, Codable, Equatable, CaseIterable {
    case secondVisit = 0
    case offerRequested = 1
    case appointmentPlanned = 2
}
