//
// Generated for Cardess.SELL
// https://github.com/yonaskolb/SwagGen
//  
//  Generated by Ilya Mikhailov
//  Copyright © 2022 MCon Germany GmbH. All rights reserved.

import Foundation



public class ExternalLeadEmailCreationResponse: Codable, Equatable {
  public var leadFound: Bool?
  public var leadId: String?
  public var messageId: String?

  public init(leadFound: Bool?  = nil, leadId: String? = nil, messageId: String? = nil) {
    self.leadFound = leadFound
    self.leadId = leadId
    self.messageId = messageId
  }


  public func isEqual(to object: Any?) -> Bool {
    guard let object = object as? ExternalLeadEmailCreationResponse else { return false }
    guard self.leadFound == object.leadFound else { return false }
    guard self.leadId == object.leadId else { return false }
    guard self.messageId == object.messageId else { return false }
    return true
  }

  public static func == (lhs: ExternalLeadEmailCreationResponse, rhs: ExternalLeadEmailCreationResponse) -> Bool {
    return lhs.isEqual(to: rhs)
  }
}
