//
// Generated for Cardess.SELL
// https://github.com/yonaskolb/SwagGen
//  
//  Generated by Ilya Mikhailov
//  Copyright © 2022 MCon Germany GmbH. All rights reserved.

import Foundation



public class ExternalLeadEmailInfo: Codable, Equatable {
  public var body: String?
  public var email: String?
  public var emailType: ExternalLeadEmailType?
  public var subject: String?

  public init(body: String?  = nil, email: String?  = nil, emailType: ExternalLeadEmailType?  = nil, subject: String?  = nil) {
    self.body = body
    self.email = email
    self.emailType = emailType
    self.subject = subject
  }


  public func isEqual(to object: Any?) -> Bool {
    guard let object = object as? ExternalLeadEmailInfo else { return false }
    guard self.body == object.body else { return false }
    guard self.email == object.email else { return false }
    guard self.emailType == object.emailType else { return false }
    guard self.subject == object.subject else { return false }
    return true
  }

  public static func == (lhs: ExternalLeadEmailInfo, rhs: ExternalLeadEmailInfo) -> Bool {
    return lhs.isEqual(to: rhs)
  }
}
