//
// Generated for Cardess.SELL
// https://github.com/yonaskolb/SwagGen
//  
//  Generated by Ilya Mikhailov
//  Copyright © 2022 MCon Germany GmbH. All rights reserved.

import Foundation

public enum ExternalLeadEmailType: Int, Codable, Equatable, CaseIterable {
    case inbound = 0
    case outbound = 1
}
