//
// Generated for Cardess.SELL
// https://github.com/yonaskolb/SwagGen
//  
//  Generated by Ilya Mikhailov
//  Copyright © 2022 MCon Germany GmbH. All rights reserved.

import Foundation



public class FacebookPageSubscription: Codable, Equatable {
  public var data: [SubscriptionData]?

  public init(data: [SubscriptionData]?  = nil) {
    self.data = data
  }


  public func isEqual(to object: Any?) -> Bool {
    guard let object = object as? FacebookPageSubscription else { return false }
    guard self.data == object.data else { return false }
    return true
  }

  public static func == (lhs: FacebookPageSubscription, rhs: FacebookPageSubscription) -> Bool {
    return lhs.isEqual(to: rhs)
  }
}
