//
// Generated for Cardess.SELL
// https://github.com/yonaskolb/SwagGen
//  
//  Generated by Ilya Mikhailov
//  Copyright © 2022 MCon Germany GmbH. All rights reserved.

import Foundation



public class FacebookBusiness: Codable, Equatable {
  public var id: String?
  public var name: String?
  public var picture: PictureDataContainer?

  public init(id: String?  = nil, name: String?  = nil, picture: PictureDataContainer?  = nil) {
    self.id = id
    self.name = name
    self.picture = picture
  }


  public func isEqual(to object: Any?) -> Bool {
    guard let object = object as? FacebookBusiness else { return false }
    guard self.id == object.id else { return false }
    guard self.name == object.name else { return false }
    guard self.picture == object.picture else { return false }
    return true
  }

  public static func == (lhs: FacebookBusiness, rhs: FacebookBusiness) -> Bool {
    return lhs.isEqual(to: rhs)
  }
}
