//
// Generated for Cardess.SELL
// https://github.com/yonaskolb/SwagGen
//  
//  Generated by Ilya Mikhailov
//  Copyright © 2022 MCon Germany GmbH. All rights reserved.

import Foundation



public class FacebookWABusiness: Codable, Equatable {
  public var id: String?
  public var name: String?
  public var phoneNumbers: [FacebookWAPhoneNumber]?

  public init(id: String?  = nil, name: String?  = nil, phoneNumbers: [FacebookWAPhoneNumber]?  = nil) {
    self.id = id
    self.name = name
    self.phoneNumbers = phoneNumbers
  }


  public func isEqual(to object: Any?) -> Bool {
    guard let object = object as? FacebookWABusiness else { return false }
    guard self.id == object.id else { return false }
    guard self.name == object.name else { return false }
    guard self.phoneNumbers == object.phoneNumbers else { return false }
    return true
  }

  public static func == (lhs: FacebookWABusiness, rhs: FacebookWABusiness) -> Bool {
    return lhs.isEqual(to: rhs)
  }
}
