//
// Generated for Cardess.SELL
// https://github.com/yonaskolb/SwagGen
//  
//  Generated by Ilya Mikhailov
//  Copyright © 2022 MCon Germany GmbH. All rights reserved.

import Foundation



public class FacebookWAContainer: Codable, Equatable {
  public var facebookBusinesses: FacebookBusiness?
  public var waAccounts: [FacebookWABusiness]?

  public init(facebookBusinesses: FacebookBusiness?  = nil, waAccounts: [FacebookWABusiness]?  = nil) {
    self.facebookBusinesses = facebookBusinesses
    self.waAccounts = waAccounts
  }


  public func isEqual(to object: Any?) -> Bool {
    guard let object = object as? FacebookWAContainer else { return false }
    guard self.facebookBusinesses == object.facebookBusinesses else { return false }
    guard self.waAccounts == object.waAccounts else { return false }
    return true
  }

  public static func == (lhs: FacebookWAContainer, rhs: FacebookWAContainer) -> Bool {
    return lhs.isEqual(to: rhs)
  }
}
