//
// Generated for Cardess.SELL
// https://github.com/yonaskolb/SwagGen
//  
//  Generated by Ilya Mikhailov
//  Copyright © 2022 MCon Germany GmbH. All rights reserved.

import Foundation



public class FilterItemInfo: Codable, Equatable {
  public var field: String?
  public var value: String?

  public init(field: String?  = nil, value: String?  = nil) {
    self.field = field
    self.value = value
  }


  public func isEqual(to object: Any?) -> Bool {
    guard let object = object as? FilterItemInfo else { return false }
    guard self.field == object.field else { return false }
    guard self.value == object.value else { return false }
    return true
  }

  public static func == (lhs: FilterItemInfo, rhs: FilterItemInfo) -> Bool {
    return lhs.isEqual(to: rhs)
  }
}
