//
// Generated for Cardess.SELL
// https://github.com/yonaskolb/SwagGen
//  
//  Generated by Ilya Mikhailov
//  Copyright © 2022 MCon Germany GmbH. All rights reserved.

import Foundation



public class HooksWhatsappComponent: Codable, Equatable {
  public var example: HooksWhatsappExample?
  public var format: String?
  public var text: String?
  public var type: String?

  public init(example: HooksWhatsappExample?  = nil, format: String?  = nil, text: String?  = nil, type: String?  = nil) {
    self.example = example
    self.format = format
    self.text = text
    self.type = type
  }


  public func isEqual(to object: Any?) -> Bool {
    guard let object = object as? HooksWhatsappComponent else { return false }
    guard self.example == object.example else { return false }
    guard self.format == object.format else { return false }
    guard self.text == object.text else { return false }
    guard self.type == object.type else { return false }
    return true
  }

  public static func == (lhs: HooksWhatsappComponent, rhs: HooksWhatsappComponent) -> Bool {
    return lhs.isEqual(to: rhs)
  }
}
