//
// Generated for Cardess.SELL
// https://github.com/yonaskolb/SwagGen
//  
//  Generated by Ilya Mikhailov
//  Copyright © 2022 MCon Germany GmbH. All rights reserved.

import Foundation



public class HooksWhatsappThroughput: Codable, Equatable {
  public var level: String?

  public init(level: String?  = nil) {
    self.level = level
  }


  public func isEqual(to object: Any?) -> Bool {
    guard let object = object as? HooksWhatsappThroughput else { return false }
    guard self.level == object.level else { return false }
    return true
  }

  public static func == (lhs: HooksWhatsappThroughput, rhs: HooksWhatsappThroughput) -> Bool {
    return lhs.isEqual(to: rhs)
  }
}
