//
// Generated for Cardess.SELL
// https://github.com/yonaskolb/SwagGen
//  
//  Generated by Ilya Mikhailov
//  Copyright © 2022 MCon Germany GmbH. All rights reserved.

import Foundation



public class HooksWhatsappWAPhoneNumber: Codable, Equatable {
  public var codeVerificationStatus: String?
  public var displayPhoneNumber: String?
  public var id: String?
  public var platformType: String?
  public var qualityRating: String?
  public var throughput: HooksWhatsappThroughput?
  public var verifiedName: String?

  public init(codeVerificationStatus: String?  = nil, displayPhoneNumber: String?  = nil, id: String?  = nil, platformType: String?  = nil, qualityRating: String?  = nil, throughput: HooksWhatsappThroughput?  = nil, verifiedName: String?  = nil) {
    self.codeVerificationStatus = codeVerificationStatus
    self.displayPhoneNumber = displayPhoneNumber
    self.id = id
    self.platformType = platformType
    self.qualityRating = qualityRating
    self.throughput = throughput
    self.verifiedName = verifiedName
  }


  public func isEqual(to object: Any?) -> Bool {
    guard let object = object as? HooksWhatsappWAPhoneNumber else { return false }
    guard self.codeVerificationStatus == object.codeVerificationStatus else { return false }
    guard self.displayPhoneNumber == object.displayPhoneNumber else { return false }
    guard self.id == object.id else { return false }
    guard self.platformType == object.platformType else { return false }
    guard self.qualityRating == object.qualityRating else { return false }
    guard self.throughput == object.throughput else { return false }
    guard self.verifiedName == object.verifiedName else { return false }
    return true
  }

  public static func == (lhs: HooksWhatsappWAPhoneNumber, rhs: HooksWhatsappWAPhoneNumber) -> Bool {
    return lhs.isEqual(to: rhs)
  }
}
