//
// Generated for Cardess.SELL
// https://github.com/yonaskolb/SwagGen
//  
//  Generated by Ilya Mikhailov
//  Copyright © 2022 MCon Germany GmbH. All rights reserved.

import Foundation



public class ImageDocmosis: Codable, Equatable {
  public var src: String?

  public init(src: String?  = nil) {
    self.src = src
  }


  public func isEqual(to object: Any?) -> Bool {
    guard let object = object as? ImageDocmosis else { return false }
    guard self.src == object.src else { return false }
    return true
  }

  public static func == (lhs: ImageDocmosis, rhs: ImageDocmosis) -> Bool {
    return lhs.isEqual(to: rhs)
  }
}
