//
// Generated for Cardess.SELL
// https://github.com/yonaskolb/SwagGen
//  
//  Generated by Ilya Mikhailov
//  Copyright © 2022 MCon Germany GmbH. All rights reserved.

import Foundation



public class ImportRequestlessThanExternalLeadVehiclegreaterThan: Codable, Equatable {
  public var entity: ExternalLeadVehicle?
  public var messageId: String?

  public init(entity: ExternalLeadVehicle?  = nil, messageId: String?  = nil) {
    self.entity = entity
    self.messageId = messageId
  }


  public func isEqual(to object: Any?) -> Bool {
    guard let object = object as? ImportRequestlessThanExternalLeadVehiclegreaterThan else { return false }
    guard self.entity == object.entity else { return false }
    guard self.messageId == object.messageId else { return false }
    return true
  }

  public static func == (lhs: ImportRequestlessThanExternalLeadVehiclegreaterThan, rhs: ImportRequestlessThanExternalLeadVehiclegreaterThan) -> Bool {
    return lhs.isEqual(to: rhs)
  }
}
