//
// Generated for Cardess.SELL
// https://github.com/yonaskolb/SwagGen
//  
//  Generated by Ilya Mikhailov
//  Copyright © 2022 MCon Germany GmbH. All rights reserved.

import Foundation



public class ImportBulkRequestlessThanExternalLeadVehiclegreaterThan: Codable, Equatable {
  public var request: [ImportRequestlessThanExternalLeadVehiclegreaterThan]?

  public init(request: [ImportRequestlessThanExternalLeadVehiclegreaterThan]?  = nil) {
    self.request = request
  }


  public func isEqual(to object: Any?) -> Bool {
    guard let object = object as? ImportBulkRequestlessThanExternalLeadVehiclegreaterThan else { return false }
    guard self.request == object.request else { return false }
    return true
  }

  public static func == (lhs: ImportBulkRequestlessThanExternalLeadVehiclegreaterThan, rhs: ImportBulkRequestlessThanExternalLeadVehiclegreaterThan) -> Bool {
    return lhs.isEqual(to: rhs)
  }
}
