//
// Generated for Cardess.SELL
// https://github.com/yonaskolb/SwagGen
//  
//  Generated by Ilya Mikhailov
//  Copyright © 2022 MCon Germany GmbH. All rights reserved.

import Foundation



public class KeyValuePairlessThanStringStringgreaterThan: Codable, Equatable {
  public var key: String?
  public var value: String?

  public init(key: String?  = nil, value: String?  = nil) {
    self.key = key
    self.value = value
  }


  public func isEqual(to object: Any?) -> Bool {
    guard let object = object as? KeyValuePairlessThanStringStringgreaterThan else { return false }
    guard self.key == object.key else { return false }
    guard self.value == object.value else { return false }
    return true
  }

  public static func == (lhs: KeyValuePairlessThanStringStringgreaterThan, rhs: KeyValuePairlessThanStringStringgreaterThan) -> Bool {
    return lhs.isEqual(to: rhs)
  }
}
