//
// Generated for Cardess.SELL
// https://github.com/yonaskolb/SwagGen
//  
//  Generated by Ilya Mikhailov
//  Copyright © 2022 MCon Germany GmbH. All rights reserved.

import Foundation



public class LeadRequestAutoRespondSettingsTriggerTypeInfo: Codable, Equatable {
  public var id: String?
  public var mappingId: String?
  public var triggerType: EnumsEngageTriggerType?

  public init(id: String? = nil, mappingId: String? = nil, triggerType: EnumsEngageTriggerType?  = nil) {
    self.id = id
    self.mappingId = mappingId
    self.triggerType = triggerType
  }


  public func isEqual(to object: Any?) -> Bool {
    guard let object = object as? LeadRequestAutoRespondSettingsTriggerTypeInfo else { return false }
    guard self.id == object.id else { return false }
    guard self.mappingId == object.mappingId else { return false }
    guard self.triggerType == object.triggerType else { return false }
    return true
  }

  public static func == (lhs: LeadRequestAutoRespondSettingsTriggerTypeInfo, rhs: LeadRequestAutoRespondSettingsTriggerTypeInfo) -> Bool {
    return lhs.isEqual(to: rhs)
  }
}
