//
// Generated for Cardess.SELL
// https://github.com/yonaskolb/SwagGen
//  
//  Generated by Ilya Mikhailov
//  Copyright © 2022 MCon Germany GmbH. All rights reserved.

import Foundation



public class LeadExportLogInfo: Codable, Equatable {
  public var errorMessage: String?
  public var exportEvent: EnumsLeadExportEvent?
  public var exportedAt: Date?
  public var id: String?
  public var isExported: Bool?
  public var leadDescription: String?
  public var leadId: String?

  public init(errorMessage: String?  = nil, exportEvent: EnumsLeadExportEvent?  = nil, exportedAt: Date? = nil, id: String? = nil, isExported: Bool?  = nil, leadDescription: String?  = nil, leadId: String? = nil) {
    self.errorMessage = errorMessage
    self.exportEvent = exportEvent
    self.exportedAt = exportedAt
    self.id = id
    self.isExported = isExported
    self.leadDescription = leadDescription
    self.leadId = leadId
  }


  public func isEqual(to object: Any?) -> Bool {
    guard let object = object as? LeadExportLogInfo else { return false }
    guard self.errorMessage == object.errorMessage else { return false }
    guard self.exportEvent == object.exportEvent else { return false }
    guard self.exportedAt == object.exportedAt else { return false }
    guard self.id == object.id else { return false }
    guard self.isExported == object.isExported else { return false }
    guard self.leadDescription == object.leadDescription else { return false }
    guard self.leadId == object.leadId else { return false }
    return true
  }

  public static func == (lhs: LeadExportLogInfo, rhs: LeadExportLogInfo) -> Bool {
    return lhs.isEqual(to: rhs)
  }
}
