//
// Generated for Cardess.SELL
// https://github.com/yonaskolb/SwagGen
//  
//  Generated by Ilya Mikhailov
//  Copyright © 2022 MCon Germany GmbH. All rights reserved.

import Foundation



public class LeadVehicleCalculationInfo: Codable, Equatable {
  public var calculationId: String?
  public var calculationType: EnumsLeadVehicleCalculationType?
  public var id: String?
  public var leadVehicleId: String?

  public init(calculationId: String? = nil, calculationType: EnumsLeadVehicleCalculationType?  = nil, id: String? = nil, leadVehicleId: String? = nil) {
    self.calculationId = calculationId
    self.calculationType = calculationType
    self.id = id
    self.leadVehicleId = leadVehicleId
  }


  public func isEqual(to object: Any?) -> Bool {
    guard let object = object as? LeadVehicleCalculationInfo else { return false }
    guard self.calculationId == object.calculationId else { return false }
    guard self.calculationType == object.calculationType else { return false }
    guard self.id == object.id else { return false }
    guard self.leadVehicleId == object.leadVehicleId else { return false }
    return true
  }

  public static func == (lhs: LeadVehicleCalculationInfo, rhs: LeadVehicleCalculationInfo) -> Bool {
    return lhs.isEqual(to: rhs)
  }
}
