//
// Generated for Cardess.SELL
// https://github.com/yonaskolb/SwagGen
//  
//  Generated by Ilya Mikhailov
//  Copyright © 2022 MCon Germany GmbH. All rights reserved.

import Foundation



public class LeadHistoryData: Codable, Equatable {
  public var events: [LeadEventInfo]?
  public var leadId: String?
  public var tags: [MasterDataTagInfo]?

  public init(events: [LeadEventInfo]?  = nil, leadId: String? = nil, tags: [MasterDataTagInfo]?  = nil) {
    self.events = events
    self.leadId = leadId
    self.tags = tags
  }


  public func isEqual(to object: Any?) -> Bool {
    guard let object = object as? LeadHistoryData else { return false }
    guard self.events == object.events else { return false }
    guard self.leadId == object.leadId else { return false }
    guard self.tags == object.tags else { return false }
    return true
  }

  public static func == (lhs: LeadHistoryData, rhs: LeadHistoryData) -> Bool {
    return lhs.isEqual(to: rhs)
  }
}
