//
// Generated for Cardess.SELL
// https://github.com/yonaskolb/SwagGen
//  
//  Generated by Ilya Mikhailov
//  Copyright © 2022 MCon Germany GmbH. All rights reserved.

import Foundation



public class LeadRequestAutoRespondSettingsMappingInfo: Codable, Equatable {
  public var id: String?
  public var leadSource: CustomerDataEnumsLeadSource?
  public var mappings: [LeadRequestAutoRespondSettingsInfo]?
  public var triggerTypes: [LeadRequestAutoRespondSettingsTriggerTypeInfo]?

  public init(id: String? = nil, leadSource: CustomerDataEnumsLeadSource?  = nil, mappings: [LeadRequestAutoRespondSettingsInfo]?  = nil, triggerTypes: [LeadRequestAutoRespondSettingsTriggerTypeInfo]?  = nil) {
    self.id = id
    self.leadSource = leadSource
    self.mappings = mappings
    self.triggerTypes = triggerTypes
  }


  public func isEqual(to object: Any?) -> Bool {
    guard let object = object as? LeadRequestAutoRespondSettingsMappingInfo else { return false }
    guard self.id == object.id else { return false }
    guard self.leadSource == object.leadSource else { return false }
    guard self.mappings == object.mappings else { return false }
    guard self.triggerTypes == object.triggerTypes else { return false }
    return true
  }

  public static func == (lhs: LeadRequestAutoRespondSettingsMappingInfo, rhs: LeadRequestAutoRespondSettingsMappingInfo) -> Bool {
    return lhs.isEqual(to: rhs)
  }
}
