//
// Generated for Cardess.SELL
// https://github.com/yonaskolb/SwagGen
//  
//  Generated by Ilya Mikhailov
//  Copyright © 2022 MCon Germany GmbH. All rights reserved.

import Foundation

public enum MasterDataEnumsPushType: Int, Codable, Equatable, CaseIterable {
    case none = 0
    case walkIn = 1
    case testDrive = 2
    case silent = 3
    case webcam = 4
}
