//
// Generated for Cardess.SELL
// https://github.com/yonaskolb/SwagGen
//  
//  Generated by Ilya Mikhailov
//  Copyright © 2022 MCon Germany GmbH. All rights reserved.

import Foundation

public enum MasterDataEnumsDataFormat: Int, Codable, Equatable, CaseIterable {
    case mobiledeExtZip = 0
    case locosoft = 1
    case facebook = 2
    case mobiledeApi = 3
    case carmeraZip = 4
    case facebookShop = 5
    case werWieSo = 6
}
