//
// Generated for Cardess.SELL
// https://github.com/yonaskolb/SwagGen
//  
//  Generated by Ilya Mikhailov
//  Copyright © 2022 MCon Germany GmbH. All rights reserved.

import Foundation

public enum MasterDataEquipmentCategoryType: Int, Codable, Equatable, CaseIterable {
    case standard = 0
    case mobileDe = 1
    case autoscout = 2
}
