//
// Generated for Cardess.SELL
// https://github.com/yonaskolb/SwagGen
//  
//  Generated by Ilya Mikhailov
//  Copyright © 2022 MCon Germany GmbH. All rights reserved.

import Foundation



public class MasterDataColourInfo: Codable, Equatable {
  public var b: Int?
  public var code: String?
  public var colorType: String?
  public var g: Int?
  public var id: String?
  public var image: String?
  public var name: String?
  public var oemId: String?
  public var price: Double?
  public var r: Int?
  public var type: String?

  public init(b: Int?  = nil, code: String?  = nil, colorType: String?  = nil, g: Int?  = nil, id: String? = nil, image: String?  = nil, name: String?  = nil, oemId: String?  = nil, price: Double?  = nil, r: Int?  = nil, type: String?  = nil) {
    self.b = b
    self.code = code
    self.colorType = colorType
    self.g = g
    self.id = id
    self.image = image
    self.name = name
    self.oemId = oemId
    self.price = price
    self.r = r
    self.type = type
  }


  public func isEqual(to object: Any?) -> Bool {
    guard let object = object as? MasterDataColourInfo else { return false }
    guard self.b == object.b else { return false }
    guard self.code == object.code else { return false }
    guard self.colorType == object.colorType else { return false }
    guard self.g == object.g else { return false }
    guard self.id == object.id else { return false }
    guard self.image == object.image else { return false }
    guard self.name == object.name else { return false }
    guard self.oemId == object.oemId else { return false }
    guard self.price == object.price else { return false }
    guard self.r == object.r else { return false }
    guard self.type == object.type else { return false }
    return true
  }

  public static func == (lhs: MasterDataColourInfo, rhs: MasterDataColourInfo) -> Bool {
    return lhs.isEqual(to: rhs)
  }
}
