//
// Generated for Cardess.SELL
// https://github.com/yonaskolb/SwagGen
//  
//  Generated by Ilya Mikhailov
//  Copyright © 2022 MCon Germany GmbH. All rights reserved.

import Foundation



public class MasterDataExportMappingItemInfo: Codable, Equatable {
  public var dataFormat: MasterDataEnumsDataFormat?
  public var from: String?
  public var id: String?
  public var property: MasterDataEnumsExportProperty?
  public var to: String?
  public var useForImport: Bool?

  public init(dataFormat: MasterDataEnumsDataFormat?  = nil, from: String?  = nil, id: String? = nil, property: MasterDataEnumsExportProperty?  = nil, to: String?  = nil, useForImport: Bool?  = nil) {
    self.dataFormat = dataFormat
    self.from = from
    self.id = id
    self.property = property
    self.to = to
    self.useForImport = useForImport
  }


  public func isEqual(to object: Any?) -> Bool {
    guard let object = object as? MasterDataExportMappingItemInfo else { return false }
    guard self.dataFormat == object.dataFormat else { return false }
    guard self.from == object.from else { return false }
    guard self.id == object.id else { return false }
    guard self.property == object.property else { return false }
    guard self.to == object.to else { return false }
    guard self.useForImport == object.useForImport else { return false }
    return true
  }

  public static func == (lhs: MasterDataExportMappingItemInfo, rhs: MasterDataExportMappingItemInfo) -> Bool {
    return lhs.isEqual(to: rhs)
  }
}
