//
// Generated for Cardess.SELL
// https://github.com/yonaskolb/SwagGen
//  
//  Generated by Ilya Mikhailov
//  Copyright © 2022 MCon Germany GmbH. All rights reserved.

import Foundation



public class MasterDataTagInfo: Codable, Equatable {
  public var category: String?
  public var categoryId: String?
  public var id: String?
  public var mainValue: String?
  public var searchWeight: Double?
  public var synonymId: String?
  public var value: String?

  public init(category: String?  = nil, categoryId: String? = nil, id: String? = nil, mainValue: String?  = nil, searchWeight: Double?  = nil, synonymId: String? = nil, value: String?  = nil) {
    self.category = category
    self.categoryId = categoryId
    self.id = id
    self.mainValue = mainValue
    self.searchWeight = searchWeight
    self.synonymId = synonymId
    self.value = value
  }


  public func isEqual(to object: Any?) -> Bool {
    guard let object = object as? MasterDataTagInfo else { return false }
    guard self.category == object.category else { return false }
    guard self.categoryId == object.categoryId else { return false }
    guard self.id == object.id else { return false }
    guard self.mainValue == object.mainValue else { return false }
    guard self.searchWeight == object.searchWeight else { return false }
    guard self.synonymId == object.synonymId else { return false }
    guard self.value == object.value else { return false }
    return true
  }

  public static func == (lhs: MasterDataTagInfo, rhs: MasterDataTagInfo) -> Bool {
    return lhs.isEqual(to: rhs)
  }
}
