//
// Generated for Cardess.SELL
// https://github.com/yonaskolb/SwagGen
//  
//  Generated by Ilya Mikhailov
//  Copyright © 2022 MCon Germany GmbH. All rights reserved.

import Foundation

public enum MasterDataEnumsOptionCategory: Int, Codable, Equatable, CaseIterable {
    case brakes = 0
    case convenience = 1
    case driverAssistanceSystems = 2
    case drivetrain = 3
    case ecoFeature = 4
    case exterior = 5
    case infotainment = 6
    case interior = 7
    case paint = 8
    case safety = 9
    case seasonalPackage = 10
    case seats = 11
    case security = 12
    case suspension = 13
    case transmission = 14
    case visibility = 15
    case wheelsTyres = 16
    case other = 17
}
