//
// Generated for Cardess.SELL
// https://github.com/yonaskolb/SwagGen
//  
//  Generated by Ilya Mikhailov
//  Copyright © 2022 MCon Germany GmbH. All rights reserved.

import Foundation



public class MasterDataVehicleConfigurationInfo: Codable, Equatable {
  public var carline: MasterDataTaxonomyCarlineInfo?
  public var colours: [MasterDataColourInfo]?
  public var generation: MasterDataTaxonomyGenerationInfo?
  public var id: String?
  public var images: [String]?
  public var make: MasterDataTaxonomyMakeInfo?
  public var model: MasterDataTaxonomyModelInfo?
  public var modelline: MasterDataTaxonomyModellineInfo?
  public var motorization: MasterDataTaxonomyMotorizationInfo?
  public var oemCode: String?
  public var options: [MasterDataTaxonomyOptionInfo]?
  public var packages: [MasterDataTaxonomyOptionPackageInfo]?
  public var rims: [MasterDataRimInfo]?
  public var upholsteries: [MasterDataUpholsteryInfo]?

  public init(carline: MasterDataTaxonomyCarlineInfo?  = nil, colours: [MasterDataColourInfo]?  = nil, generation: MasterDataTaxonomyGenerationInfo?  = nil, id: String? = nil, images: [String]?  = nil, make: MasterDataTaxonomyMakeInfo?  = nil, model: MasterDataTaxonomyModelInfo?  = nil, modelline: MasterDataTaxonomyModellineInfo?  = nil, motorization: MasterDataTaxonomyMotorizationInfo?  = nil, oemCode: String?  = nil, options: [MasterDataTaxonomyOptionInfo]?  = nil, packages: [MasterDataTaxonomyOptionPackageInfo]?  = nil, rims: [MasterDataRimInfo]?  = nil, upholsteries: [MasterDataUpholsteryInfo]?  = nil) {
    self.carline = carline
    self.colours = colours
    self.generation = generation
    self.id = id
    self.images = images
    self.make = make
    self.model = model
    self.modelline = modelline
    self.motorization = motorization
    self.oemCode = oemCode
    self.options = options
    self.packages = packages
    self.rims = rims
    self.upholsteries = upholsteries
  }


  public func isEqual(to object: Any?) -> Bool {
    guard let object = object as? MasterDataVehicleConfigurationInfo else { return false }
    guard self.carline == object.carline else { return false }
    guard self.colours == object.colours else { return false }
    guard self.generation == object.generation else { return false }
    guard self.id == object.id else { return false }
    guard self.images == object.images else { return false }
    guard self.make == object.make else { return false }
    guard self.model == object.model else { return false }
    guard self.modelline == object.modelline else { return false }
    guard self.motorization == object.motorization else { return false }
    guard self.oemCode == object.oemCode else { return false }
    guard self.options == object.options else { return false }
    guard self.packages == object.packages else { return false }
    guard self.rims == object.rims else { return false }
    guard self.upholsteries == object.upholsteries else { return false }
    return true
  }

  public static func == (lhs: MasterDataVehicleConfigurationInfo, rhs: MasterDataVehicleConfigurationInfo) -> Bool {
    return lhs.isEqual(to: rhs)
  }
}
