//
// Generated for Cardess.SELL
// https://github.com/yonaskolb/SwagGen
//  
//  Generated by Ilya Mikhailov
//  Copyright © 2022 MCon Germany GmbH. All rights reserved.

import Foundation



public class MasterDataTaxonomyModellineInfo: Codable, Equatable {
  public var deliveryPeriod: Int?
  public var description: String?
  public var generationId: String?
  public var id: String?
  public var image: String?
  public var images: [String]?
  public var manufacturerCode: String?
  public var modelBrochureUrl: String?
  public var modelPriceListUrl: String?
  public var motorizations: [MasterDataTaxonomyMotorizationInfo]?
  public var name: String?
  public var optionPackages: [MasterDataTaxonomyOptionPackageInfo]?
  public var options: [MasterDataTaxonomyOptionInfo]?
  public var price: Double?
  public var richDescription: String?

  public init(deliveryPeriod: Int?  = nil, description: String?  = nil, generationId: String? = nil, id: String? = nil, image: String?  = nil, images: [String]?  = nil, manufacturerCode: String?  = nil, modelBrochureUrl: String?  = nil, modelPriceListUrl: String?  = nil, motorizations: [MasterDataTaxonomyMotorizationInfo]?  = nil, name: String?  = nil, optionPackages: [MasterDataTaxonomyOptionPackageInfo]?  = nil, options: [MasterDataTaxonomyOptionInfo]?  = nil, price: Double?  = nil, richDescription: String?  = nil) {
    self.deliveryPeriod = deliveryPeriod
    self.description = description
    self.generationId = generationId
    self.id = id
    self.image = image
    self.images = images
    self.manufacturerCode = manufacturerCode
    self.modelBrochureUrl = modelBrochureUrl
    self.modelPriceListUrl = modelPriceListUrl
    self.motorizations = motorizations
    self.name = name
    self.optionPackages = optionPackages
    self.options = options
    self.price = price
    self.richDescription = richDescription
  }


  public func isEqual(to object: Any?) -> Bool {
    guard let object = object as? MasterDataTaxonomyModellineInfo else { return false }
    guard self.deliveryPeriod == object.deliveryPeriod else { return false }
    guard self.description == object.description else { return false }
    guard self.generationId == object.generationId else { return false }
    guard self.id == object.id else { return false }
    guard self.image == object.image else { return false }
    guard self.images == object.images else { return false }
    guard self.manufacturerCode == object.manufacturerCode else { return false }
    guard self.modelBrochureUrl == object.modelBrochureUrl else { return false }
    guard self.modelPriceListUrl == object.modelPriceListUrl else { return false }
    guard self.motorizations == object.motorizations else { return false }
    guard self.name == object.name else { return false }
    guard self.optionPackages == object.optionPackages else { return false }
    guard self.options == object.options else { return false }
    guard self.price == object.price else { return false }
    guard self.richDescription == object.richDescription else { return false }
    return true
  }

  public static func == (lhs: MasterDataTaxonomyModellineInfo, rhs: MasterDataTaxonomyModellineInfo) -> Bool {
    return lhs.isEqual(to: rhs)
  }
}
