//
// Generated for Cardess.SELL
// https://github.com/yonaskolb/SwagGen
//  
//  Generated by Ilya Mikhailov
//  Copyright © 2022 MCon Germany GmbH. All rights reserved.

import Foundation



public class MasterDataCountryInfo: Codable, Equatable {
  public var cities: [MasterDataCityInfo]?
  public var code: String?
  public var id: String?
  public var name: String?

  public init(cities: [MasterDataCityInfo]?  = nil, code: String?  = nil, id: String? = nil, name: String?  = nil) {
    self.cities = cities
    self.code = code
    self.id = id
    self.name = name
  }


  public func isEqual(to object: Any?) -> Bool {
    guard let object = object as? MasterDataCountryInfo else { return false }
    guard self.cities == object.cities else { return false }
    guard self.code == object.code else { return false }
    guard self.id == object.id else { return false }
    guard self.name == object.name else { return false }
    return true
  }

  public static func == (lhs: MasterDataCountryInfo, rhs: MasterDataCountryInfo) -> Bool {
    return lhs.isEqual(to: rhs)
  }
}
