//
// Generated for Cardess.SELL
// https://github.com/yonaskolb/SwagGen
//  
//  Generated by Ilya Mikhailov
//  Copyright © 2022 MCon Germany GmbH. All rights reserved.

import Foundation

public enum MasterDataEnumsExportProperty: Int, Codable, Equatable, CaseIterable {
    case fuelType = 0
    case transmission = 1
    case vehicleCategory = 2
    case emissionClass = 3
}
