//
// Generated for Cardess.SELL
// https://github.com/yonaskolb/SwagGen
//  
//  Generated by Ilya Mikhailov
//  Copyright © 2022 MCon Germany GmbH. All rights reserved.

import Foundation



public class MasterDataTaxonomyMakeInfo: Codable, Equatable {
  public var carLines: [MasterDataTaxonomyCarlineInfo]?
  public var description: String?
  public var id: String?
  public var image: String?
  public var images: [String]?
  public var manufacturerCode: String?
  public var name: String?

  public init(carLines: [MasterDataTaxonomyCarlineInfo]?  = nil, description: String?  = nil, id: String? = nil, image: String?  = nil, images: [String]?  = nil, manufacturerCode: String?  = nil, name: String?  = nil) {
    self.carLines = carLines
    self.description = description
    self.id = id
    self.image = image
    self.images = images
    self.manufacturerCode = manufacturerCode
    self.name = name
  }


  public func isEqual(to object: Any?) -> Bool {
    guard let object = object as? MasterDataTaxonomyMakeInfo else { return false }
    guard self.carLines == object.carLines else { return false }
    guard self.description == object.description else { return false }
    guard self.id == object.id else { return false }
    guard self.image == object.image else { return false }
    guard self.images == object.images else { return false }
    guard self.manufacturerCode == object.manufacturerCode else { return false }
    guard self.name == object.name else { return false }
    return true
  }

  public static func == (lhs: MasterDataTaxonomyMakeInfo, rhs: MasterDataTaxonomyMakeInfo) -> Bool {
    return lhs.isEqual(to: rhs)
  }
}
