//
// Generated for Cardess.SELL
// https://github.com/yonaskolb/SwagGen
//  
//  Generated by Ilya Mikhailov
//  Copyright © 2022 MCon Germany GmbH. All rights reserved.

import Foundation



public class ModelLeadTag: Codable, Equatable {
  public var id: String?
  public var lead: ModelLead?
  public var leadId: String?
  public var tagId: String?

  public init(id: String? = nil, lead: ModelLead?  = nil, leadId: String? = nil, tagId: String? = nil) {
    self.id = id
    self.lead = lead
    self.leadId = leadId
    self.tagId = tagId
  }


  public func isEqual(to object: Any?) -> Bool {
    guard let object = object as? ModelLeadTag else { return false }
    guard self.id == object.id else { return false }
    guard self.lead == object.lead else { return false }
    guard self.leadId == object.leadId else { return false }
    guard self.tagId == object.tagId else { return false }
    return true
  }

  public static func == (lhs: ModelLeadTag, rhs: ModelLeadTag) -> Bool {
    return lhs.isEqual(to: rhs)
  }
}
