//
// Generated for Cardess.SELL
// https://github.com/yonaskolb/SwagGen
//  
//  Generated by Ilya Mikhailov
//  Copyright © 2022 MCon Germany GmbH. All rights reserved.

import Foundation



public class ModelUser: Codable, Equatable {
  public var callRedirectSettings: [ModelCallRedirectSettings]?
  public var email: String?
  public var externalAccountId: String?
  public var id: String?
  public var isActive: Bool?
  public var jobTitle: String?
  public var leadAutoAssignSettings: [ModelLeadAutoAssignSettings]?
  public var leadSourceTimeframeSettings: [ModelLeadSourceTimeframeSettings]?
  public var locale: String?
  public var locationId: String?
  public var login: String?
  public var name: String?
  public var password: String?
  public var phoneNo: String?
  public var profileImage: String?
  public var signature: String?
  public var state: EnumsUserState?
  public var type: EnumsUserType?
  public var userRoles: [ModelUserRole]?
  public var views: [ModelGridView]?

  public init(callRedirectSettings: [ModelCallRedirectSettings]?  = nil, email: String?  = nil, externalAccountId: String?  = nil, id: String? = nil, isActive: Bool?  = nil, jobTitle: String?  = nil, leadAutoAssignSettings: [ModelLeadAutoAssignSettings]?  = nil, leadSourceTimeframeSettings: [ModelLeadSourceTimeframeSettings]?  = nil, locale: String?  = nil, locationId: String?  = nil, login: String?  = nil, name: String?  = nil, password: String?  = nil, phoneNo: String?  = nil, profileImage: String?  = nil, signature: String?  = nil, state: EnumsUserState?  = nil, type: EnumsUserType?  = nil, userRoles: [ModelUserRole]?  = nil, views: [ModelGridView]?  = nil) {
    self.callRedirectSettings = callRedirectSettings
    self.email = email
    self.externalAccountId = externalAccountId
    self.id = id
    self.isActive = isActive
    self.jobTitle = jobTitle
    self.leadAutoAssignSettings = leadAutoAssignSettings
    self.leadSourceTimeframeSettings = leadSourceTimeframeSettings
    self.locale = locale
    self.locationId = locationId
    self.login = login
    self.name = name
    self.password = password
    self.phoneNo = phoneNo
    self.profileImage = profileImage
    self.signature = signature
    self.state = state
    self.type = type
    self.userRoles = userRoles
    self.views = views
  }


  public func isEqual(to object: Any?) -> Bool {
    guard let object = object as? ModelUser else { return false }
    guard self.callRedirectSettings == object.callRedirectSettings else { return false }
    guard self.email == object.email else { return false }
    guard self.externalAccountId == object.externalAccountId else { return false }
    guard self.id == object.id else { return false }
    guard self.isActive == object.isActive else { return false }
    guard self.jobTitle == object.jobTitle else { return false }
    guard self.leadAutoAssignSettings == object.leadAutoAssignSettings else { return false }
    guard self.leadSourceTimeframeSettings == object.leadSourceTimeframeSettings else { return false }
    guard self.locale == object.locale else { return false }
    guard self.locationId == object.locationId else { return false }
    guard self.login == object.login else { return false }
    guard self.name == object.name else { return false }
    guard self.password == object.password else { return false }
    guard self.phoneNo == object.phoneNo else { return false }
    guard self.profileImage == object.profileImage else { return false }
    guard self.signature == object.signature else { return false }
    guard self.state == object.state else { return false }
    guard self.type == object.type else { return false }
    guard self.userRoles == object.userRoles else { return false }
    guard self.views == object.views else { return false }
    return true
  }

  public static func == (lhs: ModelUser, rhs: ModelUser) -> Bool {
    return lhs.isEqual(to: rhs)
  }
}
