//
// Generated for Cardess.SELL
// https://github.com/yonaskolb/SwagGen
//  
//  Generated by Ilya Mikhailov
//  Copyright © 2022 MCon Germany GmbH. All rights reserved.

import Foundation



public class ModelLeadVehicle: Codable, Equatable {
  public var aboRate: Double?
  public var accessories: [ModelLeadVehicleAccessory]?
  public var applicationType: CommunicationModelsEnumsApplicationType?
  public var balloon: Double?
  public var calculations: [ModelLeadVehicleCalculation]?
  public var colourId: String?
  public var comment: String?
  public var createdOn: Date?
  public var creditPeriod: Double?
  public var dealerDiscountRuleId: String?
  public var dealerLocationId: String?
  public var desiredMonthlyRateBrutto: Double?
  public var desiredMonthlyRateNetto: Double?
  public var documents: [ModelLeadVehicleDocument]?
  public var expectedAnnualMileage: Double?
  public var expirationDate: Date?
  public var id: String?
  public var isBusinessCustomer: Bool?
  public var isInsurancePackageIncluded: Bool?
  public var isServicePackageIncluded: Bool?
  public var lead: ModelLead?
  public var leadId: String?
  public var leadVehicleType: CommunicationModelsEnumsLeadVehicleType?
  public var matrixRuleId: String?
  public var modifiedOn: Date?
  public var onlineProcessId: String?
  public var orderProvidedAt: Date?
  public var payment: CommunicationModelsEnumsTypeOfPayment?
  public var prepayedAmount: Double?
  public var price: Double?
  public var reason: CommunicationModelsEnumsRejectionReason?
  public var rimId: String?
  public var upholsteryId: String?
  public var usedInTestDrive: Bool?
  public var vehicleBookingId: String?
  public var vehicleId: String?

  public init(aboRate: Double?  = nil, accessories: [ModelLeadVehicleAccessory]?  = nil, applicationType: CommunicationModelsEnumsApplicationType?  = nil, balloon: Double?  = nil, calculations: [ModelLeadVehicleCalculation]?  = nil, colourId: String? = nil, comment: String?  = nil, createdOn: Date? = nil, creditPeriod: Double?  = nil, dealerDiscountRuleId: String? = nil, dealerLocationId: String?  = nil, desiredMonthlyRateBrutto: Double?  = nil, desiredMonthlyRateNetto: Double?  = nil, documents: [ModelLeadVehicleDocument]?  = nil, expectedAnnualMileage: Double?  = nil, expirationDate: Date? = nil, id: String? = nil, isBusinessCustomer: Bool?  = nil, isInsurancePackageIncluded: Bool?  = nil, isServicePackageIncluded: Bool?  = nil, lead: ModelLead?  = nil, leadId: String? = nil, leadVehicleType: CommunicationModelsEnumsLeadVehicleType?  = nil, matrixRuleId: String? = nil, modifiedOn: Date? = nil, onlineProcessId: String? = nil, orderProvidedAt: Date? = nil, payment: CommunicationModelsEnumsTypeOfPayment?  = nil, prepayedAmount: Double?  = nil, price: Double?  = nil, reason: CommunicationModelsEnumsRejectionReason?  = nil, rimId: String? = nil, upholsteryId: String? = nil, usedInTestDrive: Bool?  = nil, vehicleBookingId: String? = nil, vehicleId: String? = nil) {
    self.aboRate = aboRate
    self.accessories = accessories
    self.applicationType = applicationType
    self.balloon = balloon
    self.calculations = calculations
    self.colourId = colourId
    self.comment = comment
    self.createdOn = createdOn
    self.creditPeriod = creditPeriod
    self.dealerDiscountRuleId = dealerDiscountRuleId
    self.dealerLocationId = dealerLocationId
    self.desiredMonthlyRateBrutto = desiredMonthlyRateBrutto
    self.desiredMonthlyRateNetto = desiredMonthlyRateNetto
    self.documents = documents
    self.expectedAnnualMileage = expectedAnnualMileage
    self.expirationDate = expirationDate
    self.id = id
    self.isBusinessCustomer = isBusinessCustomer
    self.isInsurancePackageIncluded = isInsurancePackageIncluded
    self.isServicePackageIncluded = isServicePackageIncluded
    self.lead = lead
    self.leadId = leadId
    self.leadVehicleType = leadVehicleType
    self.matrixRuleId = matrixRuleId
    self.modifiedOn = modifiedOn
    self.onlineProcessId = onlineProcessId
    self.orderProvidedAt = orderProvidedAt
    self.payment = payment
    self.prepayedAmount = prepayedAmount
    self.price = price
    self.reason = reason
    self.rimId = rimId
    self.upholsteryId = upholsteryId
    self.usedInTestDrive = usedInTestDrive
    self.vehicleBookingId = vehicleBookingId
    self.vehicleId = vehicleId
  }


  public func isEqual(to object: Any?) -> Bool {
    guard let object = object as? ModelLeadVehicle else { return false }
    guard self.aboRate == object.aboRate else { return false }
    guard self.accessories == object.accessories else { return false }
    guard self.applicationType == object.applicationType else { return false }
    guard self.balloon == object.balloon else { return false }
    guard self.calculations == object.calculations else { return false }
    guard self.colourId == object.colourId else { return false }
    guard self.comment == object.comment else { return false }
    guard self.createdOn == object.createdOn else { return false }
    guard self.creditPeriod == object.creditPeriod else { return false }
    guard self.dealerDiscountRuleId == object.dealerDiscountRuleId else { return false }
    guard self.dealerLocationId == object.dealerLocationId else { return false }
    guard self.desiredMonthlyRateBrutto == object.desiredMonthlyRateBrutto else { return false }
    guard self.desiredMonthlyRateNetto == object.desiredMonthlyRateNetto else { return false }
    guard self.documents == object.documents else { return false }
    guard self.expectedAnnualMileage == object.expectedAnnualMileage else { return false }
    guard self.expirationDate == object.expirationDate else { return false }
    guard self.id == object.id else { return false }
    guard self.isBusinessCustomer == object.isBusinessCustomer else { return false }
    guard self.isInsurancePackageIncluded == object.isInsurancePackageIncluded else { return false }
    guard self.isServicePackageIncluded == object.isServicePackageIncluded else { return false }
    guard self.lead == object.lead else { return false }
    guard self.leadId == object.leadId else { return false }
    guard self.leadVehicleType == object.leadVehicleType else { return false }
    guard self.matrixRuleId == object.matrixRuleId else { return false }
    guard self.modifiedOn == object.modifiedOn else { return false }
    guard self.onlineProcessId == object.onlineProcessId else { return false }
    guard self.orderProvidedAt == object.orderProvidedAt else { return false }
    guard self.payment == object.payment else { return false }
    guard self.prepayedAmount == object.prepayedAmount else { return false }
    guard self.price == object.price else { return false }
    guard self.reason == object.reason else { return false }
    guard self.rimId == object.rimId else { return false }
    guard self.upholsteryId == object.upholsteryId else { return false }
    guard self.usedInTestDrive == object.usedInTestDrive else { return false }
    guard self.vehicleBookingId == object.vehicleBookingId else { return false }
    guard self.vehicleId == object.vehicleId else { return false }
    return true
  }

  public static func == (lhs: ModelLeadVehicle, rhs: ModelLeadVehicle) -> Bool {
    return lhs.isEqual(to: rhs)
  }
}
