//
// Generated for Cardess.SELL
// https://github.com/yonaskolb/SwagGen
//  
//  Generated by Ilya Mikhailov
//  Copyright © 2022 MCon Germany GmbH. All rights reserved.

import Foundation



public class ModelLeadObjection: Codable, Equatable {
  public var createdOn: Date?
  public var id: String?
  public var lead: ModelLead?
  public var leadId: String?
  public var modifiedOn: Date?
  public var objection: ModelObjection?
  public var objectionId: String?

  public init(createdOn: Date? = nil, id: String? = nil, lead: ModelLead?  = nil, leadId: String? = nil, modifiedOn: Date? = nil, objection: ModelObjection?  = nil, objectionId: String? = nil) {
    self.createdOn = createdOn
    self.id = id
    self.lead = lead
    self.leadId = leadId
    self.modifiedOn = modifiedOn
    self.objection = objection
    self.objectionId = objectionId
  }


  public func isEqual(to object: Any?) -> Bool {
    guard let object = object as? ModelLeadObjection else { return false }
    guard self.createdOn == object.createdOn else { return false }
    guard self.id == object.id else { return false }
    guard self.lead == object.lead else { return false }
    guard self.leadId == object.leadId else { return false }
    guard self.modifiedOn == object.modifiedOn else { return false }
    guard self.objection == object.objection else { return false }
    guard self.objectionId == object.objectionId else { return false }
    return true
  }

  public static func == (lhs: ModelLeadObjection, rhs: ModelLeadObjection) -> Bool {
    return lhs.isEqual(to: rhs)
  }
}
