//
// Generated for Cardess.SELL
// https://github.com/yonaskolb/SwagGen
//  
//  Generated by Ilya Mikhailov
//  Copyright © 2022 MCon Germany GmbH. All rights reserved.

import Foundation



public class ModelResource: Codable, Equatable {
  public var activities: [ModelActivity]?
  public var id: String?
  public var type: EnumsResourceType?

  public init(activities: [ModelActivity]?  = nil, id: String? = nil, type: EnumsResourceType?  = nil) {
    self.activities = activities
    self.id = id
    self.type = type
  }


  public func isEqual(to object: Any?) -> Bool {
    guard let object = object as? ModelResource else { return false }
    guard self.activities == object.activities else { return false }
    guard self.id == object.id else { return false }
    guard self.type == object.type else { return false }
    return true
  }

  public static func == (lhs: ModelResource, rhs: ModelResource) -> Bool {
    return lhs.isEqual(to: rhs)
  }
}
