//
// Generated for Cardess.SELL
// https://github.com/yonaskolb/SwagGen
//  
//  Generated by Ilya Mikhailov
//  Copyright © 2022 MCon Germany GmbH. All rights reserved.

import Foundation



public class ModelLeadVehicleDocument: Codable, Equatable {
  public var documentPurpose: EnumsLeadVehicleDocumentPurpose?
  public var documentType: EnumsLeadVehicleDocumentType?
  public var id: String?
  public var leadVehicle: ModelLeadVehicle?
  public var leadVehicleId: String?
  public var name: String?

  public init(documentPurpose: EnumsLeadVehicleDocumentPurpose?  = nil, documentType: EnumsLeadVehicleDocumentType?  = nil, id: String? = nil, leadVehicle: ModelLeadVehicle?  = nil, leadVehicleId: String? = nil, name: String?  = nil) {
    self.documentPurpose = documentPurpose
    self.documentType = documentType
    self.id = id
    self.leadVehicle = leadVehicle
    self.leadVehicleId = leadVehicleId
    self.name = name
  }


  public func isEqual(to object: Any?) -> Bool {
    guard let object = object as? ModelLeadVehicleDocument else { return false }
    guard self.documentPurpose == object.documentPurpose else { return false }
    guard self.documentType == object.documentType else { return false }
    guard self.id == object.id else { return false }
    guard self.leadVehicle == object.leadVehicle else { return false }
    guard self.leadVehicleId == object.leadVehicleId else { return false }
    guard self.name == object.name else { return false }
    return true
  }

  public static func == (lhs: ModelLeadVehicleDocument, rhs: ModelLeadVehicleDocument) -> Bool {
    return lhs.isEqual(to: rhs)
  }
}
