//
// Generated for Cardess.SELL
// https://github.com/yonaskolb/SwagGen
//  
//  Generated by Ilya Mikhailov
//  Copyright © 2022 MCon Germany GmbH. All rights reserved.

import Foundation



public class ModelRole: Codable, Equatable {
  public var id: String?
  public var name: String?
  public var userRoles: [ModelUserRole]?

  public init(id: String? = nil, name: String?  = nil, userRoles: [ModelUserRole]?  = nil) {
    self.id = id
    self.name = name
    self.userRoles = userRoles
  }


  public func isEqual(to object: Any?) -> Bool {
    guard let object = object as? ModelRole else { return false }
    guard self.id == object.id else { return false }
    guard self.name == object.name else { return false }
    guard self.userRoles == object.userRoles else { return false }
    return true
  }

  public static func == (lhs: ModelRole, rhs: ModelRole) -> Bool {
    return lhs.isEqual(to: rhs)
  }
}
