//
// Generated for Cardess.SELL
// https://github.com/yonaskolb/SwagGen
//  
//  Generated by Ilya Mikhailov
//  Copyright © 2022 MCon Germany GmbH. All rights reserved.

import Foundation



public class ModelObjection: Codable, Equatable {
  public var createdOn: Date?
  public var id: String?
  public var modifiedOn: Date?
  public var text: String?

  public init(createdOn: Date? = nil, id: String? = nil, modifiedOn: Date? = nil, text: String?  = nil) {
    self.createdOn = createdOn
    self.id = id
    self.modifiedOn = modifiedOn
    self.text = text
  }


  public func isEqual(to object: Any?) -> Bool {
    guard let object = object as? ModelObjection else { return false }
    guard self.createdOn == object.createdOn else { return false }
    guard self.id == object.id else { return false }
    guard self.modifiedOn == object.modifiedOn else { return false }
    guard self.text == object.text else { return false }
    return true
  }

  public static func == (lhs: ModelObjection, rhs: ModelObjection) -> Bool {
    return lhs.isEqual(to: rhs)
  }
}
