//
// Generated for Cardess.SELL
// https://github.com/yonaskolb/SwagGen
//  
//  Generated by Ilya Mikhailov
//  Copyright © 2022 MCon Germany GmbH. All rights reserved.

import Foundation



public class ParsingSource: Codable, Equatable {
  public var attributes: [String]?
  public var leadSource: Int?
  public var source: String?
  public var targetSystem: String?
  public var uploadPath: String?

  public init(attributes: [String]?  = nil, leadSource: Int?  = nil, source: String?  = nil, targetSystem: String?  = nil, uploadPath: String?  = nil) {
    self.attributes = attributes
    self.leadSource = leadSource
    self.source = source
    self.targetSystem = targetSystem
    self.uploadPath = uploadPath
  }


  public func isEqual(to object: Any?) -> Bool {
    guard let object = object as? ParsingSource else { return false }
    guard self.attributes == object.attributes else { return false }
    guard self.leadSource == object.leadSource else { return false }
    guard self.source == object.source else { return false }
    guard self.targetSystem == object.targetSystem else { return false }
    guard self.uploadPath == object.uploadPath else { return false }
    return true
  }

  public static func == (lhs: ParsingSource, rhs: ParsingSource) -> Bool {
    return lhs.isEqual(to: rhs)
  }
}
