//
// Generated for Cardess.SELL
// https://github.com/yonaskolb/SwagGen
//  
//  Generated by Ilya Mikhailov
//  Copyright © 2022 MCon Germany GmbH. All rights reserved.

import Foundation



public class ParsingSetting: Codable, Equatable {
  public var eMail: String?
  public var errorReceiver: String?
  public var forwardReceivers: String?
  public var locationID: Int?
  public var mainContacts: String?
  public var mandantID: Int?
  public var source: String?

  public init(eMail: String?  = nil, errorReceiver: String?  = nil, forwardReceivers: String?  = nil, locationID: Int?  = nil, mainContacts: String?  = nil, mandantID: Int?  = nil, source: String?  = nil) {
    self.eMail = eMail
    self.errorReceiver = errorReceiver
    self.forwardReceivers = forwardReceivers
    self.locationID = locationID
    self.mainContacts = mainContacts
    self.mandantID = mandantID
    self.source = source
  }


  public func isEqual(to object: Any?) -> Bool {
    guard let object = object as? ParsingSetting else { return false }
    guard self.eMail == object.eMail else { return false }
    guard self.errorReceiver == object.errorReceiver else { return false }
    guard self.forwardReceivers == object.forwardReceivers else { return false }
    guard self.locationID == object.locationID else { return false }
    guard self.mainContacts == object.mainContacts else { return false }
    guard self.mandantID == object.mandantID else { return false }
    guard self.source == object.source else { return false }
    return true
  }

  public static func == (lhs: ParsingSetting, rhs: ParsingSetting) -> Bool {
    return lhs.isEqual(to: rhs)
  }
}
