//
// Generated for Cardess.SELL
// https://github.com/yonaskolb/SwagGen
//  
//  Generated by Ilya Mikhailov
//  Copyright © 2022 MCon Germany GmbH. All rights reserved.

import Foundation



public class PictureData: Codable, Equatable {
  public var height: Int?
  public var isSilhouette: Bool?
  public var url: String?
  public var width: Int?

  public init(height: Int?  = nil, isSilhouette: Bool?  = nil, url: String?  = nil, width: Int?  = nil) {
    self.height = height
    self.isSilhouette = isSilhouette
    self.url = url
    self.width = width
  }


  public func isEqual(to object: Any?) -> Bool {
    guard let object = object as? PictureData else { return false }
    guard self.height == object.height else { return false }
    guard self.isSilhouette == object.isSilhouette else { return false }
    guard self.url == object.url else { return false }
    guard self.width == object.width else { return false }
    return true
  }

  public static func == (lhs: PictureData, rhs: PictureData) -> Bool {
    return lhs.isEqual(to: rhs)
  }
}
