//
// Generated for Cardess.SELL
// https://github.com/yonaskolb/SwagGen
//  
//  Generated by Ilya Mikhailov
//  Copyright © 2022 MCon Germany GmbH. All rights reserved.

import Foundation



public class PictureDataContainer: Codable, Equatable {
  public var data: PictureData?

  public init(data: PictureData?  = nil) {
    self.data = data
  }


  public func isEqual(to object: Any?) -> Bool {
    guard let object = object as? PictureDataContainer else { return false }
    guard self.data == object.data else { return false }
    return true
  }

  public static func == (lhs: PictureDataContainer, rhs: PictureDataContainer) -> Bool {
    return lhs.isEqual(to: rhs)
  }
}
