//
// Generated for Cardess.SELL
// https://github.com/yonaskolb/SwagGen
//  
//  Generated by Ilya Mikhailov
//  Copyright © 2022 MCon Germany GmbH. All rights reserved.

import Foundation



public class PriceStickerInfo: Codable, Equatable {
  public var id: String?
  public var name: String?
  public var productId: String?
  public var productType: EnumsProductType?

  public init(id: String? = nil, name: String?  = nil, productId: String? = nil, productType: EnumsProductType?  = nil) {
    self.id = id
    self.name = name
    self.productId = productId
    self.productType = productType
  }


  public func isEqual(to object: Any?) -> Bool {
    guard let object = object as? PriceStickerInfo else { return false }
    guard self.id == object.id else { return false }
    guard self.name == object.name else { return false }
    guard self.productId == object.productId else { return false }
    guard self.productType == object.productType else { return false }
    return true
  }

  public static func == (lhs: PriceStickerInfo, rhs: PriceStickerInfo) -> Bool {
    return lhs.isEqual(to: rhs)
  }
}
