//
// Generated for Cardess.SELL
// https://github.com/yonaskolb/SwagGen
//  
//  Generated by Ilya Mikhailov
//  Copyright © 2022 MCon Germany GmbH. All rights reserved.

import Foundation



public class PushData: Codable, Equatable {
  public var generalMessage: Bool?
  public var localizationKey: String?
  public var parameters: String?
  public var pushType: MasterDataEnumsPushType?
  public var titleLocalizationKey: String?

  public init(generalMessage: Bool?  = nil, localizationKey: String?  = nil, parameters: String?  = nil, pushType: MasterDataEnumsPushType?  = nil, titleLocalizationKey: String?  = nil) {
    self.generalMessage = generalMessage
    self.localizationKey = localizationKey
    self.parameters = parameters
    self.pushType = pushType
    self.titleLocalizationKey = titleLocalizationKey
  }


  public func isEqual(to object: Any?) -> Bool {
    guard let object = object as? PushData else { return false }
    guard self.generalMessage == object.generalMessage else { return false }
    guard self.localizationKey == object.localizationKey else { return false }
    guard self.parameters == object.parameters else { return false }
    guard self.pushType == object.pushType else { return false }
    guard self.titleLocalizationKey == object.titleLocalizationKey else { return false }
    return true
  }

  public static func == (lhs: PushData, rhs: PushData) -> Bool {
    return lhs.isEqual(to: rhs)
  }
}
