//
// Generated for Cardess.SELL
// https://github.com/yonaskolb/SwagGen
//  
//  Generated by Ilya Mikhailov
//  Copyright © 2022 MCon Germany GmbH. All rights reserved.

import Foundation



public class ReassignRequest: Codable, Equatable {
  public typealias ID = String
  public var allActivities: Bool?
  public var allLeads: Bool?
  public var allLeadsActivities: Bool?
  public var fromUserId: String?
  public var process: Bool?
  public var toUserIds: [ID]?

  public init(allActivities: Bool?  = nil, allLeads: Bool?  = nil, allLeadsActivities: Bool?  = nil, fromUserId: String? = nil, process: Bool?  = nil, toUserIds: [ID]?  = nil) {
    self.allActivities = allActivities
    self.allLeads = allLeads
    self.allLeadsActivities = allLeadsActivities
    self.fromUserId = fromUserId
    self.process = process
    self.toUserIds = toUserIds
  }


  public func isEqual(to object: Any?) -> Bool {
    guard let object = object as? ReassignRequest else { return false }
    guard self.allActivities == object.allActivities else { return false }
    guard self.allLeads == object.allLeads else { return false }
    guard self.allLeadsActivities == object.allLeadsActivities else { return false }
    guard self.fromUserId == object.fromUserId else { return false }
    guard self.process == object.process else { return false }
    guard self.toUserIds == object.toUserIds else { return false }
    return true
  }

  public static func == (lhs: ReassignRequest, rhs: ReassignRequest) -> Bool {
    return lhs.isEqual(to: rhs)
  }
}
