//
// Generated for Cardess.SELL
// https://github.com/yonaskolb/SwagGen
//  
//  Generated by Ilya Mikhailov
//  Copyright © 2022 MCon Germany GmbH. All rights reserved.

import Foundation



public class ReassignResponse: Codable, Equatable {
  public var activitiesReassigned: Int?
  public var leadsReassigned: Int?

  public init(activitiesReassigned: Int?  = nil, leadsReassigned: Int?  = nil) {
    self.activitiesReassigned = activitiesReassigned
    self.leadsReassigned = leadsReassigned
  }


  public func isEqual(to object: Any?) -> Bool {
    guard let object = object as? ReassignResponse else { return false }
    guard self.activitiesReassigned == object.activitiesReassigned else { return false }
    guard self.leadsReassigned == object.leadsReassigned else { return false }
    return true
  }

  public static func == (lhs: ReassignResponse, rhs: ReassignResponse) -> Bool {
    return lhs.isEqual(to: rhs)
  }
}
