//
// Generated for Cardess.SELL
// https://github.com/yonaskolb/SwagGen
//  
//  Generated by Ilya Mikhailov
//  Copyright © 2022 MCon Germany GmbH. All rights reserved.

import Foundation



public class RedirectData: Codable, Equatable {
  public var activityId: String?
  public var isHangUp: Bool?
  public var leadVehicleId: String?
  public var phoneNo: String?
  public var redirectTo: String?
  public var redirectToFallBack: Bool?
  public var redirectToReception: Bool?
  public var remoteLocationUrl: String?
  public var vehicleId: String?

  public init(activityId: String? = nil, isHangUp: Bool?  = nil, leadVehicleId: String? = nil, phoneNo: String?  = nil, redirectTo: String? = nil, redirectToFallBack: Bool?  = nil, redirectToReception: Bool?  = nil, remoteLocationUrl: String?  = nil, vehicleId: String? = nil) {
    self.activityId = activityId
    self.isHangUp = isHangUp
    self.leadVehicleId = leadVehicleId
    self.phoneNo = phoneNo
    self.redirectTo = redirectTo
    self.redirectToFallBack = redirectToFallBack
    self.redirectToReception = redirectToReception
    self.remoteLocationUrl = remoteLocationUrl
    self.vehicleId = vehicleId
  }


  public func isEqual(to object: Any?) -> Bool {
    guard let object = object as? RedirectData else { return false }
    guard self.activityId == object.activityId else { return false }
    guard self.isHangUp == object.isHangUp else { return false }
    guard self.leadVehicleId == object.leadVehicleId else { return false }
    guard self.phoneNo == object.phoneNo else { return false }
    guard self.redirectTo == object.redirectTo else { return false }
    guard self.redirectToFallBack == object.redirectToFallBack else { return false }
    guard self.redirectToReception == object.redirectToReception else { return false }
    guard self.remoteLocationUrl == object.remoteLocationUrl else { return false }
    guard self.vehicleId == object.vehicleId else { return false }
    return true
  }

  public static func == (lhs: RedirectData, rhs: RedirectData) -> Bool {
    return lhs.isEqual(to: rhs)
  }
}
