//
// Generated for Cardess.SELL
// https://github.com/yonaskolb/SwagGen
//  
//  Generated by Ilya Mikhailov
//  Copyright © 2022 MCon Germany GmbH. All rights reserved.

import Foundation



public class ReportGroupItem: Codable, Equatable {
  public var data: ReportData?
  public var name: String?

  public init(data: ReportData?  = nil, name: String?  = nil) {
    self.data = data
    self.name = name
  }


  public func isEqual(to object: Any?) -> Bool {
    guard let object = object as? ReportGroupItem else { return false }
    guard self.data == object.data else { return false }
    guard self.name == object.name else { return false }
    return true
  }

  public static func == (lhs: ReportGroupItem, rhs: ReportGroupItem) -> Bool {
    return lhs.isEqual(to: rhs)
  }
}
