//
// Generated for Cardess.SELL
// https://github.com/yonaskolb/SwagGen
//  
//  Generated by Ilya Mikhailov
//  Copyright © 2022 MCon Germany GmbH. All rights reserved.

import Foundation



public class RequestContactResponse: Codable, Equatable {
  public var endDate: Date?
  public var id: String?
  public var leadId: String?
  public var leadVehicleType: CommunicationModelsEnumsLeadVehicleType?
  public var startDate: Date?
  public var vehicleId: String?

  public init(endDate: Date? = nil, id: String? = nil, leadId: String? = nil, leadVehicleType: CommunicationModelsEnumsLeadVehicleType?  = nil, startDate: Date? = nil, vehicleId: String? = nil) {
    self.endDate = endDate
    self.id = id
    self.leadId = leadId
    self.leadVehicleType = leadVehicleType
    self.startDate = startDate
    self.vehicleId = vehicleId
  }


  public func isEqual(to object: Any?) -> Bool {
    guard let object = object as? RequestContactResponse else { return false }
    guard self.endDate == object.endDate else { return false }
    guard self.id == object.id else { return false }
    guard self.leadId == object.leadId else { return false }
    guard self.leadVehicleType == object.leadVehicleType else { return false }
    guard self.startDate == object.startDate else { return false }
    guard self.vehicleId == object.vehicleId else { return false }
    return true
  }

  public static func == (lhs: RequestContactResponse, rhs: RequestContactResponse) -> Bool {
    return lhs.isEqual(to: rhs)
  }
}
