//
// Generated for Cardess.SELL
// https://github.com/yonaskolb/SwagGen
//  
//  Generated by Ilya Mikhailov
//  Copyright © 2022 MCon Germany GmbH. All rights reserved.

import Foundation



public class RoleInfo: Codable, Equatable {
  public var id: String?
  public var name: String?

  public init(id: String? = nil, name: String?  = nil) {
    self.id = id
    self.name = name
  }


  public func isEqual(to object: Any?) -> Bool {
    guard let object = object as? RoleInfo else { return false }
    guard self.id == object.id else { return false }
    guard self.name == object.name else { return false }
    return true
  }

  public static func == (lhs: RoleInfo, rhs: RoleInfo) -> Bool {
    return lhs.isEqual(to: rhs)
  }
}
