//
// Generated for Cardess.SELL
// https://github.com/yonaskolb/SwagGen
//  
//  Generated by Ilya Mikhailov
//  Copyright © 2022 MCon Germany GmbH. All rights reserved.

import Foundation



public class SalesPersonDocmosis: Codable, Equatable {
  public var company: String?
  public var email: String?
  public var id: String?
  public var name: String?
  public var phone: String?
  public var position: String?
  public var profileImage: String?

  public init(company: String?  = nil, email: String?  = nil, id: String? = nil, name: String?  = nil, phone: String?  = nil, position: String?  = nil, profileImage: String?  = nil) {
    self.company = company
    self.email = email
    self.id = id
    self.name = name
    self.phone = phone
    self.position = position
    self.profileImage = profileImage
  }


  public func isEqual(to object: Any?) -> Bool {
    guard let object = object as? SalesPersonDocmosis else { return false }
    guard self.company == object.company else { return false }
    guard self.email == object.email else { return false }
    guard self.id == object.id else { return false }
    guard self.name == object.name else { return false }
    guard self.phone == object.phone else { return false }
    guard self.position == object.position else { return false }
    guard self.profileImage == object.profileImage else { return false }
    return true
  }

  public static func == (lhs: SalesPersonDocmosis, rhs: SalesPersonDocmosis) -> Bool {
    return lhs.isEqual(to: rhs)
  }
}
