//
// Generated for Cardess.SELL
// https://github.com/yonaskolb/SwagGen
//  
//  Generated by Ilya Mikhailov
//  Copyright © 2022 MCon Germany GmbH. All rights reserved.

import Foundation



public class SecurityCodeInfo: Codable, Equatable {
  public var code: Int?
  public var leadId: String?

  public init(code: Int?  = nil, leadId: String? = nil) {
    self.code = code
    self.leadId = leadId
  }


  public func isEqual(to object: Any?) -> Bool {
    guard let object = object as? SecurityCodeInfo else { return false }
    guard self.code == object.code else { return false }
    guard self.leadId == object.leadId else { return false }
    return true
  }

  public static func == (lhs: SecurityCodeInfo, rhs: SecurityCodeInfo) -> Bool {
    return lhs.isEqual(to: rhs)
  }
}
