//
// Generated for Cardess.SELL
// https://github.com/yonaskolb/SwagGen
//  
//  Generated by Ilya Mikhailov
//  Copyright © 2022 MCon Germany GmbH. All rights reserved.

import Foundation



public class ServiceDocmosis: Codable, Equatable {
  public var price: Double?
  public var title: String?
  public var type: Int?

  public init(price: Double?  = nil, title: String?  = nil, type: Int?  = nil) {
    self.price = price
    self.title = title
    self.type = type
  }


  public func isEqual(to object: Any?) -> Bool {
    guard let object = object as? ServiceDocmosis else { return false }
    guard self.price == object.price else { return false }
    guard self.title == object.title else { return false }
    guard self.type == object.type else { return false }
    return true
  }

  public static func == (lhs: ServiceDocmosis, rhs: ServiceDocmosis) -> Bool {
    return lhs.isEqual(to: rhs)
  }
}
