//
// Generated for Cardess.SELL
// https://github.com/yonaskolb/SwagGen
//  
//  Generated by Ilya Mikhailov
//  Copyright © 2022 MCon Germany GmbH. All rights reserved.

import Foundation



public class ShowroomShowroomConfiguration: Codable, Equatable {
  public var devices: [ShowroomManuelDevice]?
  public var images: [ShowroomTaggedImage]?
  public var zones: [ShowroomZone]?

  public init(devices: [ShowroomManuelDevice]?  = nil, images: [ShowroomTaggedImage]?  = nil, zones: [ShowroomZone]?  = nil) {
    self.devices = devices
    self.images = images
    self.zones = zones
  }


  public func isEqual(to object: Any?) -> Bool {
    guard let object = object as? ShowroomShowroomConfiguration else { return false }
    guard self.devices == object.devices else { return false }
    guard self.images == object.images else { return false }
    guard self.zones == object.zones else { return false }
    return true
  }

  public static func == (lhs: ShowroomShowroomConfiguration, rhs: ShowroomShowroomConfiguration) -> Bool {
    return lhs.isEqual(to: rhs)
  }
}
