//
// Generated for Cardess.SELL
// https://github.com/yonaskolb/SwagGen
//  
//  Generated by Ilya Mikhailov
//  Copyright © 2022 MCon Germany GmbH. All rights reserved.

import Foundation



public class ShowroomManuelDevice: Codable, Equatable {
  public var ip: String?
  public var name: String?

  public init(ip: String?  = nil, name: String?  = nil) {
    self.ip = ip
    self.name = name
  }


  public func isEqual(to object: Any?) -> Bool {
    guard let object = object as? ShowroomManuelDevice else { return false }
    guard self.ip == object.ip else { return false }
    guard self.name == object.name else { return false }
    return true
  }

  public static func == (lhs: ShowroomManuelDevice, rhs: ShowroomManuelDevice) -> Bool {
    return lhs.isEqual(to: rhs)
  }
}
