//
// Generated for Cardess.SELL
// https://github.com/yonaskolb/SwagGen
//  
//  Generated by Ilya Mikhailov
//  Copyright © 2022 MCon Germany GmbH. All rights reserved.

import Foundation



public class StaticDocumentInfo: Codable, Equatable {
  public var customerType: EnumsDocumentCustomerType?
  public var defaultProcessTemplatesId: String?
  public var id: String?
  public var localPath: String?
  public var name: String?
  public var payment: CommunicationModelsEnumsTypeOfPayment?
  public var type: EnumsDocumentType?

  public init(customerType: EnumsDocumentCustomerType?  = nil, defaultProcessTemplatesId: String? = nil, id: String? = nil, localPath: String?  = nil, name: String?  = nil, payment: CommunicationModelsEnumsTypeOfPayment?  = nil, type: EnumsDocumentType?  = nil) {
    self.customerType = customerType
    self.defaultProcessTemplatesId = defaultProcessTemplatesId
    self.id = id
    self.localPath = localPath
    self.name = name
    self.payment = payment
    self.type = type
  }


  public func isEqual(to object: Any?) -> Bool {
    guard let object = object as? StaticDocumentInfo else { return false }
    guard self.customerType == object.customerType else { return false }
    guard self.defaultProcessTemplatesId == object.defaultProcessTemplatesId else { return false }
    guard self.id == object.id else { return false }
    guard self.localPath == object.localPath else { return false }
    guard self.name == object.name else { return false }
    guard self.payment == object.payment else { return false }
    guard self.type == object.type else { return false }
    return true
  }

  public static func == (lhs: StaticDocumentInfo, rhs: StaticDocumentInfo) -> Bool {
    return lhs.isEqual(to: rhs)
  }
}
