//
// Generated for Cardess.SELL
// https://github.com/yonaskolb/SwagGen
//  
//  Generated by Ilya Mikhailov
//  Copyright © 2022 MCon Germany GmbH. All rights reserved.

import Foundation



public class SubscriptionData: Codable, Equatable {
  public var category: String?
  public var id: String?
  public var link: String?
  public var name: String?
  public var subscribedFields: [String]?

  public init(category: String?  = nil, id: String?  = nil, link: String?  = nil, name: String?  = nil, subscribedFields: [String]?  = nil) {
    self.category = category
    self.id = id
    self.link = link
    self.name = name
    self.subscribedFields = subscribedFields
  }


  public func isEqual(to object: Any?) -> Bool {
    guard let object = object as? SubscriptionData else { return false }
    guard self.category == object.category else { return false }
    guard self.id == object.id else { return false }
    guard self.link == object.link else { return false }
    guard self.name == object.name else { return false }
    guard self.subscribedFields == object.subscribedFields else { return false }
    return true
  }

  public static func == (lhs: SubscriptionData, rhs: SubscriptionData) -> Bool {
    return lhs.isEqual(to: rhs)
  }
}
