//
// Generated for Cardess.SELL
// https://github.com/yonaskolb/SwagGen
//  
//  Generated by Ilya Mikhailov
//  Copyright © 2022 MCon Germany GmbH. All rights reserved.

import Foundation



public class SystemTimeSpan: Codable, Equatable {
  public var days: Int?
  public var hours: Int?
  public var milliseconds: Int?
  public var minutes: Int?
  public var seconds: Int?
  public var ticks: Int?
  public var totalDays: Double?
  public var totalHours: Double?
  public var totalMilliseconds: Double?
  public var totalMinutes: Double?
  public var totalSeconds: Double?

  public init(days: Int?  = nil, hours: Int?  = nil, milliseconds: Int?  = nil, minutes: Int?  = nil, seconds: Int?  = nil, ticks: Int?  = nil, totalDays: Double?  = nil, totalHours: Double?  = nil, totalMilliseconds: Double?  = nil, totalMinutes: Double?  = nil, totalSeconds: Double?  = nil) {
    self.days = days
    self.hours = hours
    self.milliseconds = milliseconds
    self.minutes = minutes
    self.seconds = seconds
    self.ticks = ticks
    self.totalDays = totalDays
    self.totalHours = totalHours
    self.totalMilliseconds = totalMilliseconds
    self.totalMinutes = totalMinutes
    self.totalSeconds = totalSeconds
  }


  public func isEqual(to object: Any?) -> Bool {
    guard let object = object as? SystemTimeSpan else { return false }
    guard self.days == object.days else { return false }
    guard self.hours == object.hours else { return false }
    guard self.milliseconds == object.milliseconds else { return false }
    guard self.minutes == object.minutes else { return false }
    guard self.seconds == object.seconds else { return false }
    guard self.ticks == object.ticks else { return false }
    guard self.totalDays == object.totalDays else { return false }
    guard self.totalHours == object.totalHours else { return false }
    guard self.totalMilliseconds == object.totalMilliseconds else { return false }
    guard self.totalMinutes == object.totalMinutes else { return false }
    guard self.totalSeconds == object.totalSeconds else { return false }
    return true
  }

  public static func == (lhs: SystemTimeSpan, rhs: SystemTimeSpan) -> Bool {
    return lhs.isEqual(to: rhs)
  }
}
