//
// Generated for Cardess.SELL
// https://github.com/yonaskolb/SwagGen
//  
//  Generated by Ilya Mikhailov
//  Copyright © 2022 MCon Germany GmbH. All rights reserved.

import Foundation



public class TimeSlot: Codable, Equatable {
  public var end: Date?
  public var start: Date?

  public init(end: Date? = nil, start: Date? = nil) {
    self.end = end
    self.start = start
  }


  public func isEqual(to object: Any?) -> Bool {
    guard let object = object as? TimeSlot else { return false }
    guard self.end == object.end else { return false }
    guard self.start == object.start else { return false }
    return true
  }

  public static func == (lhs: TimeSlot, rhs: TimeSlot) -> Bool {
    return lhs.isEqual(to: rhs)
  }
}
