//
// Generated for Cardess.SELL
// https://github.com/yonaskolb/SwagGen
//  
//  Generated by Ilya Mikhailov
//  Copyright © 2022 MCon Germany GmbH. All rights reserved.

import Foundation



public class ToolsFailureResponse: Codable, Equatable {
  public var code: String?
  public var message: String?
  public var reason: String?

  public init(code: String?  = nil, message: String?  = nil, reason: String?  = nil) {
    self.code = code
    self.message = message
    self.reason = reason
  }


  public func isEqual(to object: Any?) -> Bool {
    guard let object = object as? ToolsFailureResponse else { return false }
    guard self.code == object.code else { return false }
    guard self.message == object.message else { return false }
    guard self.reason == object.reason else { return false }
    return true
  }

  public static func == (lhs: ToolsFailureResponse, rhs: ToolsFailureResponse) -> Bool {
    return lhs.isEqual(to: rhs)
  }
}
