//
// Generated for Cardess.SELL
// https://github.com/yonaskolb/SwagGen
//  
//  Generated by Ilya Mikhailov
//  Copyright © 2022 MCon Germany GmbH. All rights reserved.

import Foundation



public class ToolsCsvWriterCsvExportFilerItem: Codable, Equatable {
  public var controlName: String?
  public var filedName: String?
  public var `operator`: String?

  public init(controlName: String?  = nil, filedName: String?  = nil, `operator`: String?  = nil) {
    self.controlName = controlName
    self.filedName = filedName
    self.`operator` = `operator`
  }


  public func isEqual(to object: Any?) -> Bool {
    guard let object = object as? ToolsCsvWriterCsvExportFilerItem else { return false }
    guard self.controlName == object.controlName else { return false }
    guard self.filedName == object.filedName else { return false }
    guard self.`operator` == object.`operator` else { return false }
    return true
  }

  public static func == (lhs: ToolsCsvWriterCsvExportFilerItem, rhs: ToolsCsvWriterCsvExportFilerItem) -> Bool {
    return lhs.isEqual(to: rhs)
  }
}
