//
// Generated for Cardess.SELL
// https://github.com/yonaskolb/SwagGen
//  
//  Generated by Ilya Mikhailov
//  Copyright © 2022 MCon Germany GmbH. All rights reserved.

import Foundation



public class TwilioSubResource: Codable, Equatable {
  public var count: Double?
  public var countUnit: String?
  public var price: Double?
  public var priceUnit: String?
  public var usage: Double?
  public var usageUnit: String?

  public init(count: Double?  = nil, countUnit: String?  = nil, price: Double?  = nil, priceUnit: String?  = nil, usage: Double?  = nil, usageUnit: String?  = nil) {
    self.count = count
    self.countUnit = countUnit
    self.price = price
    self.priceUnit = priceUnit
    self.usage = usage
    self.usageUnit = usageUnit
  }


  public func isEqual(to object: Any?) -> Bool {
    guard let object = object as? TwilioSubResource else { return false }
    guard self.count == object.count else { return false }
    guard self.countUnit == object.countUnit else { return false }
    guard self.price == object.price else { return false }
    guard self.priceUnit == object.priceUnit else { return false }
    guard self.usage == object.usage else { return false }
    guard self.usageUnit == object.usageUnit else { return false }
    return true
  }

  public static func == (lhs: TwilioSubResource, rhs: TwilioSubResource) -> Bool {
    return lhs.isEqual(to: rhs)
  }
}
