//
// Generated for Cardess.SELL
// https://github.com/yonaskolb/SwagGen
//  
//  Generated by Ilya Mikhailov
//  Copyright © 2022 MCon Germany GmbH. All rights reserved.

import Foundation



public class TwilioBillingInfo: Codable, Equatable {
  public var categories: [TwilioBillingCategory]?
  public var totalPrice: TwilioBillingCategory?

  public init(categories: [TwilioBillingCategory]?  = nil, totalPrice: TwilioBillingCategory?  = nil) {
    self.categories = categories
    self.totalPrice = totalPrice
  }


  public func isEqual(to object: Any?) -> Bool {
    guard let object = object as? TwilioBillingInfo else { return false }
    guard self.categories == object.categories else { return false }
    guard self.totalPrice == object.totalPrice else { return false }
    return true
  }

  public static func == (lhs: TwilioBillingInfo, rhs: TwilioBillingInfo) -> Bool {
    return lhs.isEqual(to: rhs)
  }
}
