//
// Generated for Cardess.SELL
// https://github.com/yonaskolb/SwagGen
//  
//  Generated by Ilya Mikhailov
//  Copyright © 2022 MCon Germany GmbH. All rights reserved.

import Foundation



public class TwilioBillingCategory: Codable, Equatable {
  public var allTime: TwilioSubResource?
  public var currentQuarter: TwilioSubResource?
  public var description: String?
  public var lastMonth: TwilioSubResource?
  public var name: String?
  public var previousQuarter: TwilioSubResource?
  public var thisMonth: TwilioSubResource?

  public init(allTime: TwilioSubResource?  = nil, currentQuarter: TwilioSubResource?  = nil, description: String?  = nil, lastMonth: TwilioSubResource?  = nil, name: String?  = nil, previousQuarter: TwilioSubResource?  = nil, thisMonth: TwilioSubResource?  = nil) {
    self.allTime = allTime
    self.currentQuarter = currentQuarter
    self.description = description
    self.lastMonth = lastMonth
    self.name = name
    self.previousQuarter = previousQuarter
    self.thisMonth = thisMonth
  }


  public func isEqual(to object: Any?) -> Bool {
    guard let object = object as? TwilioBillingCategory else { return false }
    guard self.allTime == object.allTime else { return false }
    guard self.currentQuarter == object.currentQuarter else { return false }
    guard self.description == object.description else { return false }
    guard self.lastMonth == object.lastMonth else { return false }
    guard self.name == object.name else { return false }
    guard self.previousQuarter == object.previousQuarter else { return false }
    guard self.thisMonth == object.thisMonth else { return false }
    return true
  }

  public static func == (lhs: TwilioBillingCategory, rhs: TwilioBillingCategory) -> Bool {
    return lhs.isEqual(to: rhs)
  }
}
