//
// Generated for Cardess.SELL
// https://github.com/yonaskolb/SwagGen
//  
//  Generated by Ilya Mikhailov
//  Copyright © 2022 MCon Germany GmbH. All rights reserved.

import Foundation

public enum VehicleDataEnumsOrderStatus: Int, Codable, Equatable, CaseIterable {
    case anticipation = 0
    case inStock = 1
}
