//
// Generated for Cardess.SELL
// https://github.com/yonaskolb/SwagGen
//  
//  Generated by Ilya Mikhailov
//  Copyright © 2022 MCon Germany GmbH. All rights reserved.

import Foundation



public class VehicleDataVehicleBookingInfo: Codable, Equatable {
  public var currentMileage: Int?
  public var description: String?
  public var endPlannedMileage: Int?
  public var from: Date?
  public var id: String?
  public var leadId: String?
  public var leadName: String?
  public var leadVehicleId: String?
  public var startMileage: Int?
  public var state: VehicleDataEnumsVehicleBookingState?
  public var to: Date?
  public var type: VehicleDataEnumsVehicleBookingType?
  public var vehicleId: String?

  public init(currentMileage: Int?  = nil, description: String?  = nil, endPlannedMileage: Int?  = nil, from: Date? = nil, id: String? = nil, leadId: String? = nil, leadName: String?  = nil, leadVehicleId: String? = nil, startMileage: Int?  = nil, state: VehicleDataEnumsVehicleBookingState?  = nil, to: Date? = nil, type: VehicleDataEnumsVehicleBookingType?  = nil, vehicleId: String? = nil) {
    self.currentMileage = currentMileage
    self.description = description
    self.endPlannedMileage = endPlannedMileage
    self.from = from
    self.id = id
    self.leadId = leadId
    self.leadName = leadName
    self.leadVehicleId = leadVehicleId
    self.startMileage = startMileage
    self.state = state
    self.to = to
    self.type = type
    self.vehicleId = vehicleId
  }


  public func isEqual(to object: Any?) -> Bool {
    guard let object = object as? VehicleDataVehicleBookingInfo else { return false }
    guard self.currentMileage == object.currentMileage else { return false }
    guard self.description == object.description else { return false }
    guard self.endPlannedMileage == object.endPlannedMileage else { return false }
    guard self.from == object.from else { return false }
    guard self.id == object.id else { return false }
    guard self.leadId == object.leadId else { return false }
    guard self.leadName == object.leadName else { return false }
    guard self.leadVehicleId == object.leadVehicleId else { return false }
    guard self.startMileage == object.startMileage else { return false }
    guard self.state == object.state else { return false }
    guard self.to == object.to else { return false }
    guard self.type == object.type else { return false }
    guard self.vehicleId == object.vehicleId else { return false }
    return true
  }

  public static func == (lhs: VehicleDataVehicleBookingInfo, rhs: VehicleDataVehicleBookingInfo) -> Bool {
    return lhs.isEqual(to: rhs)
  }
}
