//
// Generated for Cardess.SELL
// https://github.com/yonaskolb/SwagGen
//  
//  Generated by Ilya Mikhailov
//  Copyright © 2022 MCon Germany GmbH. All rights reserved.

import Foundation



public class VehicleDataExportedInfo: Codable, Equatable {
  public var exportChannel: MasterDataEnumsExportChannel?
  public var exportedAt: Date?
  public var externalId: String?
  public var failed: Bool?
  public var failureReason: String?
  public var firstExportedAt: Date?
  public var id: String?
  public var key: String?
  public var retries: Int?
  public var vehicleId: String?

  public init(exportChannel: MasterDataEnumsExportChannel?  = nil, exportedAt: Date? = nil, externalId: String?  = nil, failed: Bool?  = nil, failureReason: String?  = nil, firstExportedAt: Date? = nil, id: String? = nil, key: String?  = nil, retries: Int?  = nil, vehicleId: String? = nil) {
    self.exportChannel = exportChannel
    self.exportedAt = exportedAt
    self.externalId = externalId
    self.failed = failed
    self.failureReason = failureReason
    self.firstExportedAt = firstExportedAt
    self.id = id
    self.key = key
    self.retries = retries
    self.vehicleId = vehicleId
  }


  public func isEqual(to object: Any?) -> Bool {
    guard let object = object as? VehicleDataExportedInfo else { return false }
    guard self.exportChannel == object.exportChannel else { return false }
    guard self.exportedAt == object.exportedAt else { return false }
    guard self.externalId == object.externalId else { return false }
    guard self.failed == object.failed else { return false }
    guard self.failureReason == object.failureReason else { return false }
    guard self.firstExportedAt == object.firstExportedAt else { return false }
    guard self.id == object.id else { return false }
    guard self.key == object.key else { return false }
    guard self.retries == object.retries else { return false }
    guard self.vehicleId == object.vehicleId else { return false }
    return true
  }

  public static func == (lhs: VehicleDataExportedInfo, rhs: VehicleDataExportedInfo) -> Bool {
    return lhs.isEqual(to: rhs)
  }
}
