//
// Generated for Cardess.SELL
// https://github.com/yonaskolb/SwagGen
//  
//  Generated by Ilya Mikhailov
//  Copyright © 2022 MCon Germany GmbH. All rights reserved.

import Foundation



public class VehicleDataVehicleOptionInfo: Codable, Equatable {
  public var builtin: Bool?
  public var categoryId: String?
  public var collectAv: Bool?
  public var equipmentCode: String?
  public var equipmentGroup: String?
  public var id: String?
  public var manufacturerCode: String?
  public var name: String?
  public var special: Bool?
  public var vinEquipment: Bool?

  public init(builtin: Bool?  = nil, categoryId: String?  = nil, collectAv: Bool?  = nil, equipmentCode: String?  = nil, equipmentGroup: String?  = nil, id: String? = nil, manufacturerCode: String?  = nil, name: String?  = nil, special: Bool?  = nil, vinEquipment: Bool?  = nil) {
    self.builtin = builtin
    self.categoryId = categoryId
    self.collectAv = collectAv
    self.equipmentCode = equipmentCode
    self.equipmentGroup = equipmentGroup
    self.id = id
    self.manufacturerCode = manufacturerCode
    self.name = name
    self.special = special
    self.vinEquipment = vinEquipment
  }


  public func isEqual(to object: Any?) -> Bool {
    guard let object = object as? VehicleDataVehicleOptionInfo else { return false }
    guard self.builtin == object.builtin else { return false }
    guard self.categoryId == object.categoryId else { return false }
    guard self.collectAv == object.collectAv else { return false }
    guard self.equipmentCode == object.equipmentCode else { return false }
    guard self.equipmentGroup == object.equipmentGroup else { return false }
    guard self.id == object.id else { return false }
    guard self.manufacturerCode == object.manufacturerCode else { return false }
    guard self.name == object.name else { return false }
    guard self.special == object.special else { return false }
    guard self.vinEquipment == object.vinEquipment else { return false }
    return true
  }

  public static func == (lhs: VehicleDataVehicleOptionInfo, rhs: VehicleDataVehicleOptionInfo) -> Bool {
    return lhs.isEqual(to: rhs)
  }
}
