//
// Generated for Cardess.SELL
// https://github.com/yonaskolb/SwagGen
//  
//  Generated by Ilya Mikhailov
//  Copyright © 2022 MCon Germany GmbH. All rights reserved.

import Foundation



public class VehicleDataLeasingPeriodPricesInfo: Codable, Equatable {
  public var cells: [String: VehicleDataLeasingMileagePricesInfo]?
  public var period: Int?

  public init(cells: [String: VehicleDataLeasingMileagePricesInfo]?  = nil, period: Int?  = nil) {
    self.cells = cells
    self.period = period
  }


  public func isEqual(to object: Any?) -> Bool {
    guard let object = object as? VehicleDataLeasingPeriodPricesInfo else { return false }
    guard self.cells == object.cells else { return false }
    guard self.period == object.period else { return false }
    return true
  }

  public static func == (lhs: VehicleDataLeasingPeriodPricesInfo, rhs: VehicleDataLeasingPeriodPricesInfo) -> Bool {
    return lhs.isEqual(to: rhs)
  }
}
