//
// Generated for Cardess.SELL
// https://github.com/yonaskolb/SwagGen
//  
//  Generated by Ilya Mikhailov
//  Copyright © 2022 MCon Germany GmbH. All rights reserved.

import Foundation

public enum VehicleDataEnumsEmissionsSticker: Int, Codable, Equatable, CaseIterable {
    case undefined = 0
    case noSticker = 1
    case red = 2
    case yellow = 3
    case green = 4
}
