//
// Generated for Cardess.SELL
// https://github.com/yonaskolb/SwagGen
//  
//  Generated by Ilya Mikhailov
//  Copyright © 2022 MCon Germany GmbH. All rights reserved.

import Foundation



public class VehicleDataVehicleBookingResourceInfo: Codable, Equatable {
  public var bookings: [VehicleDataVehicleBookingInfo]?
  public var id: String?
  public var licensePlate: String?
  public var locationId: String?
  public var name: String?
  public var vin: String?

  public init(bookings: [VehicleDataVehicleBookingInfo]?  = nil, id: String? = nil, licensePlate: String?  = nil, locationId: String?  = nil, name: String?  = nil, vin: String?  = nil) {
    self.bookings = bookings
    self.id = id
    self.licensePlate = licensePlate
    self.locationId = locationId
    self.name = name
    self.vin = vin
  }


  public func isEqual(to object: Any?) -> Bool {
    guard let object = object as? VehicleDataVehicleBookingResourceInfo else { return false }
    guard self.bookings == object.bookings else { return false }
    guard self.id == object.id else { return false }
    guard self.licensePlate == object.licensePlate else { return false }
    guard self.locationId == object.locationId else { return false }
    guard self.name == object.name else { return false }
    guard self.vin == object.vin else { return false }
    return true
  }

  public static func == (lhs: VehicleDataVehicleBookingResourceInfo, rhs: VehicleDataVehicleBookingResourceInfo) -> Bool {
    return lhs.isEqual(to: rhs)
  }
}
