//
// Generated for Cardess.SELL
// https://github.com/yonaskolb/SwagGen
//  
//  Generated by Ilya Mikhailov
//  Copyright © 2022 MCon Germany GmbH. All rights reserved.

import Foundation

public enum VehicleDataEnumsCampaignDefaultPrice: Int, Codable, Equatable, CaseIterable {
    case salesPriceRRP = 0
    case dealerRetailPrice = 1
}
