//
// Generated for Cardess.SELL
// https://github.com/yonaskolb/SwagGen
//  
//  Generated by Ilya Mikhailov
//  Copyright © 2022 MCon Germany GmbH. All rights reserved.

import Foundation



public class VehicleDataMatrixRuleInfo: Codable, Equatable {
  public var coefficient: Double?
  public var deactivated: Bool?
  public var id: String?
  public var matrix: VehicleDataPriceMatrixInfo?
  public var matrixId: String?
  public var name: String?
  public var ruleTags: [MasterDataTagInfo]?

  public init(coefficient: Double?  = nil, deactivated: Bool?  = nil, id: String? = nil, matrix: VehicleDataPriceMatrixInfo?  = nil, matrixId: String? = nil, name: String?  = nil, ruleTags: [MasterDataTagInfo]?  = nil) {
    self.coefficient = coefficient
    self.deactivated = deactivated
    self.id = id
    self.matrix = matrix
    self.matrixId = matrixId
    self.name = name
    self.ruleTags = ruleTags
  }


  public func isEqual(to object: Any?) -> Bool {
    guard let object = object as? VehicleDataMatrixRuleInfo else { return false }
    guard self.coefficient == object.coefficient else { return false }
    guard self.deactivated == object.deactivated else { return false }
    guard self.id == object.id else { return false }
    guard self.matrix == object.matrix else { return false }
    guard self.matrixId == object.matrixId else { return false }
    guard self.name == object.name else { return false }
    guard self.ruleTags == object.ruleTags else { return false }
    return true
  }

  public static func == (lhs: VehicleDataMatrixRuleInfo, rhs: VehicleDataMatrixRuleInfo) -> Bool {
    return lhs.isEqual(to: rhs)
  }
}
