//
// Generated for Cardess.SELL
// https://github.com/yonaskolb/SwagGen
//  
//  Generated by Ilya Mikhailov
//  Copyright © 2022 MCon Germany GmbH. All rights reserved.

import Foundation

public enum VehicleDataEnumsServiceCalculationType: Int, Codable, Equatable, CaseIterable {
    case staticPrice = 0
    case maintenance = 1
    case insurance = 2
    case delivery = 3
    case registration = 4
    case warranty = 5
    case homeDelivery = 6
}
