//
// Generated for Cardess.SELL
// https://github.com/yonaskolb/SwagGen
//  
//  Generated by Ilya Mikhailov
//  Copyright © 2022 MCon Germany GmbH. All rights reserved.

import Foundation



public class VehicleDataInstaVidStockItemData: Codable, Equatable {
  public var dealer: String?
  public var spin: String?
  public var stockNumber: String?
  public var token: String?

  public init(dealer: String?  = nil, spin: String?  = nil, stockNumber: String?  = nil, token: String?  = nil) {
    self.dealer = dealer
    self.spin = spin
    self.stockNumber = stockNumber
    self.token = token
  }


  public func isEqual(to object: Any?) -> Bool {
    guard let object = object as? VehicleDataInstaVidStockItemData else { return false }
    guard self.dealer == object.dealer else { return false }
    guard self.spin == object.spin else { return false }
    guard self.stockNumber == object.stockNumber else { return false }
    guard self.token == object.token else { return false }
    return true
  }

  public static func == (lhs: VehicleDataInstaVidStockItemData, rhs: VehicleDataInstaVidStockItemData) -> Bool {
    return lhs.isEqual(to: rhs)
  }
}
