//
// Generated for Cardess.SELL
// https://github.com/yonaskolb/SwagGen
//  
//  Generated by Ilya Mikhailov
//  Copyright © 2022 MCon Germany GmbH. All rights reserved.

import Foundation

public enum VehicleDataEnumsCalculationRuleType: Int, Codable, Equatable, CaseIterable {
    case discount = 0
    case premium = 1
    case defaultPrepayment = 2
    case deliveryPrice = 3
    case leasingCalculationCoefficient = 4
    case aboExtraKmPrice = 5
    case bdkEffectiveInterestRate = 6
    case agio = 7
    case homeDeliveryPrice = 8
    case dealerDiscount = 9
    case simpleFinancingInterestRate = 10
}
