//
// Generated for Cardess.SELL
// https://github.com/yonaskolb/SwagGen
//  
//  Generated by Ilya Mikhailov
//  Copyright © 2022 MCon Germany GmbH. All rights reserved.

import Foundation

public enum VehicleDataEnumsImportItemType: Int, Codable, Equatable, CaseIterable {
    case none = 0
    case childVehicle = 1
    case virtualImages = 2
    case hyundaiAnticipation = 3
    case kiaChildVehicle = 4
    case locosoft = 5
    case mobileDe = 6
    case carmera = 7
    case werWieSo = 8
}
