//
// Generated for Cardess.SELL
// https://github.com/yonaskolb/SwagGen
//  
//  Generated by Ilya Mikhailov
//  Copyright © 2022 MCon Germany GmbH. All rights reserved.

import Foundation

public enum VehicleDataEnumsProcessTypeOfPayment: Int, Codable, Equatable, CaseIterable {
    case cash = 0
    case leasing = 1
    case credit = 2
    case abo = 3
}
