//
// Generated for Cardess.SELL
// https://github.com/yonaskolb/SwagGen
//  
//  Generated by Ilya Mikhailov
//  Copyright © 2022 MCon Germany GmbH. All rights reserved.

import Foundation



public class VehicleDataWarningInfo: Codable, Equatable {
  public var message: String?
  public var type: String?

  public init(message: String?  = nil, type: String?  = nil) {
    self.message = message
    self.type = type
  }


  public func isEqual(to object: Any?) -> Bool {
    guard let object = object as? VehicleDataWarningInfo else { return false }
    guard self.message == object.message else { return false }
    guard self.type == object.type else { return false }
    return true
  }

  public static func == (lhs: VehicleDataWarningInfo, rhs: VehicleDataWarningInfo) -> Bool {
    return lhs.isEqual(to: rhs)
  }
}
