//
// Generated for Cardess.SELL
// https://github.com/yonaskolb/SwagGen
//  
//  Generated by Ilya Mikhailov
//  Copyright © 2022 MCon Germany GmbH. All rights reserved.

import Foundation



public class VehicleDataServiceTypeInfo: Codable, Equatable {
  public var code: String?
  public var description: String?
  public var id: String?
  public var title: String?

  public init(code: String?  = nil, description: String?  = nil, id: String? = nil, title: String?  = nil) {
    self.code = code
    self.description = description
    self.id = id
    self.title = title
  }


  public func isEqual(to object: Any?) -> Bool {
    guard let object = object as? VehicleDataServiceTypeInfo else { return false }
    guard self.code == object.code else { return false }
    guard self.description == object.description else { return false }
    guard self.id == object.id else { return false }
    guard self.title == object.title else { return false }
    return true
  }

  public static func == (lhs: VehicleDataServiceTypeInfo, rhs: VehicleDataServiceTypeInfo) -> Bool {
    return lhs.isEqual(to: rhs)
  }
}
