//
// Generated for Cardess.SELL
// https://github.com/yonaskolb/SwagGen
//  
//  Generated by Ilya Mikhailov
//  Copyright © 2022 MCon Germany GmbH. All rights reserved.

import Foundation

public enum VehicleDataEnumsVehicleStatus: Int, Codable, Equatable, CaseIterable {
    case new = 0
    case used = 1
    case demo = 2
    case customer = 3
    case virtual = 4
    case dayRegistration = 5
}
