//
// Generated for Cardess.SELL
// https://github.com/yonaskolb/SwagGen
//  
//  Generated by Ilya Mikhailov
//  Copyright © 2022 MCon Germany GmbH. All rights reserved.

import Foundation



public class VehicleDataMatrixCellInfo: Codable, Equatable {
  public var id: String?
  public var value: Double?

  public init(id: String? = nil, value: Double?  = nil) {
    self.id = id
    self.value = value
  }


  public func isEqual(to object: Any?) -> Bool {
    guard let object = object as? VehicleDataMatrixCellInfo else { return false }
    guard self.id == object.id else { return false }
    guard self.value == object.value else { return false }
    return true
  }

  public static func == (lhs: VehicleDataMatrixCellInfo, rhs: VehicleDataMatrixCellInfo) -> Bool {
    return lhs.isEqual(to: rhs)
  }
}
