//
// Generated for Cardess.SELL
// https://github.com/yonaskolb/SwagGen
//  
//  Generated by Ilya Mikhailov
//  Copyright © 2022 MCon Germany GmbH. All rights reserved.

import Foundation

public enum VehicleDataEnumsSalesStatus: Int, Codable, Equatable, CaseIterable {
    case reserved = 0
    case contracted = 1
}
