//
// Generated for Cardess.SELL
// https://github.com/yonaskolb/SwagGen
//  
//  Generated by Ilya Mikhailov
//  Copyright © 2022 MCon Germany GmbH. All rights reserved.

import Foundation



public class VehicleDataOptionPackageInfo: Codable, Equatable {
  public var description: String?
  public var id: String?
  public var image: String?
  public var isSelected: Bool?
  public var isStandard: Bool?
  public var manufacturerCode: String?
  public var name: String?
  public var options: [VehicleDataVehicleOptionInfo]?
  public var price: Double?

  public init(description: String?  = nil, id: String? = nil, image: String?  = nil, isSelected: Bool?  = nil, isStandard: Bool?  = nil, manufacturerCode: String?  = nil, name: String?  = nil, options: [VehicleDataVehicleOptionInfo]?  = nil, price: Double?  = nil) {
    self.description = description
    self.id = id
    self.image = image
    self.isSelected = isSelected
    self.isStandard = isStandard
    self.manufacturerCode = manufacturerCode
    self.name = name
    self.options = options
    self.price = price
  }


  public func isEqual(to object: Any?) -> Bool {
    guard let object = object as? VehicleDataOptionPackageInfo else { return false }
    guard self.description == object.description else { return false }
    guard self.id == object.id else { return false }
    guard self.image == object.image else { return false }
    guard self.isSelected == object.isSelected else { return false }
    guard self.isStandard == object.isStandard else { return false }
    guard self.manufacturerCode == object.manufacturerCode else { return false }
    guard self.name == object.name else { return false }
    guard self.options == object.options else { return false }
    guard self.price == object.price else { return false }
    return true
  }

  public static func == (lhs: VehicleDataOptionPackageInfo, rhs: VehicleDataOptionPackageInfo) -> Bool {
    return lhs.isEqual(to: rhs)
  }
}
