//
// Generated for Cardess.SELL
// https://github.com/yonaskolb/SwagGen
//  
//  Generated by Ilya Mikhailov
//  Copyright © 2022 MCon Germany GmbH. All rights reserved.

import Foundation



public class VehicleDataImportLogInfo: Codable, Equatable {
  public var channelName: String?
  public var errors: [VehicleDataImportErrorInfo]?
  public var finishedAt: Date?
  public var id: String?
  public var importType: VehicleDataEnumsImportItemType?
  public var importedAmount: Int?
  public var total: Int?

  public init(channelName: String?  = nil, errors: [VehicleDataImportErrorInfo]?  = nil, finishedAt: Date? = nil, id: String? = nil, importType: VehicleDataEnumsImportItemType?  = nil, importedAmount: Int?  = nil, total: Int?  = nil) {
    self.channelName = channelName
    self.errors = errors
    self.finishedAt = finishedAt
    self.id = id
    self.importType = importType
    self.importedAmount = importedAmount
    self.total = total
  }


  public func isEqual(to object: Any?) -> Bool {
    guard let object = object as? VehicleDataImportLogInfo else { return false }
    guard self.channelName == object.channelName else { return false }
    guard self.errors == object.errors else { return false }
    guard self.finishedAt == object.finishedAt else { return false }
    guard self.id == object.id else { return false }
    guard self.importType == object.importType else { return false }
    guard self.importedAmount == object.importedAmount else { return false }
    guard self.total == object.total else { return false }
    return true
  }

  public static func == (lhs: VehicleDataImportLogInfo, rhs: VehicleDataImportLogInfo) -> Bool {
    return lhs.isEqual(to: rhs)
  }
}
