//
// Generated for Cardess.SELL
// https://github.com/yonaskolb/SwagGen
//  
//  Generated by Ilya Mikhailov
//  Copyright © 2022 MCon Germany GmbH. All rights reserved.

import Foundation



public class VehicleDataCampaignInfo: Codable, Equatable {
  public var code: String?
  public var defaultBallonPercent: Double?
  public var defaultBallonPrice: VehicleDataEnumsCampaignDefaultPrice?
  public var defaultDepositPercent: Double?
  public var defaultDepositPrice: VehicleDataEnumsCampaignDefaultPrice?
  public var defaultMileage: Int?
  public var defaultPeriod: Int?
  public var depositPlusBallonMaxPercent: Double?
  public var id: String?
  public var name: String?
  public var state: VehicleDataEnumsCampaignState?

  public init(code: String?  = nil, defaultBallonPercent: Double?  = nil, defaultBallonPrice: VehicleDataEnumsCampaignDefaultPrice?  = nil, defaultDepositPercent: Double?  = nil, defaultDepositPrice: VehicleDataEnumsCampaignDefaultPrice?  = nil, defaultMileage: Int?  = nil, defaultPeriod: Int?  = nil, depositPlusBallonMaxPercent: Double?  = nil, id: String? = nil, name: String?  = nil, state: VehicleDataEnumsCampaignState?  = nil) {
    self.code = code
    self.defaultBallonPercent = defaultBallonPercent
    self.defaultBallonPrice = defaultBallonPrice
    self.defaultDepositPercent = defaultDepositPercent
    self.defaultDepositPrice = defaultDepositPrice
    self.defaultMileage = defaultMileage
    self.defaultPeriod = defaultPeriod
    self.depositPlusBallonMaxPercent = depositPlusBallonMaxPercent
    self.id = id
    self.name = name
    self.state = state
  }


  public func isEqual(to object: Any?) -> Bool {
    guard let object = object as? VehicleDataCampaignInfo else { return false }
    guard self.code == object.code else { return false }
    guard self.defaultBallonPercent == object.defaultBallonPercent else { return false }
    guard self.defaultBallonPrice == object.defaultBallonPrice else { return false }
    guard self.defaultDepositPercent == object.defaultDepositPercent else { return false }
    guard self.defaultDepositPrice == object.defaultDepositPrice else { return false }
    guard self.defaultMileage == object.defaultMileage else { return false }
    guard self.defaultPeriod == object.defaultPeriod else { return false }
    guard self.depositPlusBallonMaxPercent == object.depositPlusBallonMaxPercent else { return false }
    guard self.id == object.id else { return false }
    guard self.name == object.name else { return false }
    guard self.state == object.state else { return false }
    return true
  }

  public static func == (lhs: VehicleDataCampaignInfo, rhs: VehicleDataCampaignInfo) -> Bool {
    return lhs.isEqual(to: rhs)
  }
}
