//
// Generated for Cardess.SELL
// https://github.com/yonaskolb/SwagGen
//  
//  Generated by Ilya Mikhailov
//  Copyright © 2022 MCon Germany GmbH. All rights reserved.

import Foundation

public enum VehicleDataEnumsMatrixState: Int, Codable, Equatable, CaseIterable {
    case draft = 0
    case active = 1
    case archive = 2
}
