//
// Generated for Cardess.SELL
// https://github.com/yonaskolb/SwagGen
//  
//  Generated by Ilya Mikhailov
//  Copyright © 2022 MCon Germany GmbH. All rights reserved.

import Foundation

public enum VehicleDataEnumsCampaignState: Int, Codable, Equatable, CaseIterable {
    case draft = 0
    case started = 1
    case finished = 2
    case canceled = 3
}
