//
// Generated for Cardess.SELL
// https://github.com/yonaskolb/SwagGen
//  
//  Generated by Ilya Mikhailov
//  Copyright © 2022 MCon Germany GmbH. All rights reserved.

import Foundation



public class VideoRoomInfo: Codable, Equatable {
  public var roomName: String?
  public var token: String?

  public init(roomName: String?  = nil, token: String?  = nil) {
    self.roomName = roomName
    self.token = token
  }


  public func isEqual(to object: Any?) -> Bool {
    guard let object = object as? VideoRoomInfo else { return false }
    guard self.roomName == object.roomName else { return false }
    guard self.token == object.token else { return false }
    return true
  }

  public static func == (lhs: VideoRoomInfo, rhs: VideoRoomInfo) -> Bool {
    return lhs.isEqual(to: rhs)
  }
}
